### ISSUE TITLE
Brackets can appear out of alignment depending on the size given to the terminal

### ISSUE THREAD

**Issue by Porkepix** [googlefonts/noto-fonts#1131] opened 2018-04-05 14:51 UTC
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Brackets can appear out of alignment depending on the size given to the terminal

### Font 
NotoSansMono-Regular.ttf 

### Where the font came from, and when
 https://www.archlinux.org/packages/extra/any/noto-fonts/
Built from https://github.com/googlei18n/noto-fonts/archive/b207fc31b093948dfc6d77b47042ce2f335bc631.tar.gz

### Font Version
  > 2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)

### OS name and version
  > Archlinux

### Application name and version
  > Gnome terminal, Terminator, Terminology…

### Issue
  > Brackets can be misaligned with big or tiny font size

  1. Change your terminal and therefore font size to a big or tiny size
  2. Type brackets
  3. See that this is misaligned
  4. It should be aligned

### Screenshot
![screenshot from 2018-04-05 16-49-11](https://user-images.githubusercontent.com/709500/38373392-7764a1e6-38f1-11e8-9e9b-a039e83f1a55.png)
![screenshot from 2018-04-05 16-49-26](https://user-images.githubusercontent.com/709500/38373393-777febea-38f1-11e8-940a-0acd28b9c666.png)
![screenshot from 2018-04-05 16-50-22](https://user-images.githubusercontent.com/709500/38373394-77a06852-38f1-11e8-921b-d2a73ccf95e8.png)

It's more difficult to see on the big version and my eyes can trick me, but I think there's a one or two pixels difference.

**Comment by xry111** [comment] 2019-03-20 18:09
With size 12 or 15 all brackets ("[]", "()", and "{}") misaligns.  With size 14 only "{}" misaligns.  So I can only use size 13 now...

**Comment by xry111** [comment] 2019-03-20 18:45
This issue only exists in hinted version.

**Comment by veaceslav** [comment] 2020-10-05 12:32
I have the same problem, when using Pycharm with Noto Sans Mono:

![image](https://user-images.githubusercontent.com/2550683/95079868-80b63880-0717-11eb-94c5-08992e1a401d.png)

**Comment by the-shank** [comment] 2020-10-05 14:04
@veaceslav I got it to work by setting hinting to none in font settings for the desktop environment (in my case xfce).

**Comment by veaceslav** [comment] 2020-10-05 14:14
I tried with my KDE environment, and the problem is still present... I have other mono fonts to use, but It was slightly annoying to find this misalignment :)

**Comment by simoncozens** [comment] 2022-04-22 13:52
It's not just the hinting - the brackets really were out of alignment. But I think this is now fixed; see #2103.

**Closed by simoncozens** 2022-04-22 13:52 UTC
Labels: Script-Monospace
