### ISSUE TITLE
Elements of cyrillic letters are not rendered evenly

### ISSUE THREAD

**Issue by soviet-man** [googlefonts/noto-fonts#1025] opened 2018-01-05 22:40 UTC
Some capital cyrillic letters look like parts of them are not rendered evenly.
For example, here we have capital letters 'Ш', 'Н', 'М'
![default](https://user-images.githubusercontent.com/33825590/34631625-55296a22-f282-11e7-881d-484567025f83.png)
Right post of letter 'Ш' visually look thiner than left one. Same for 'М'.

Font: Noto Sans
Face: Regular
Size: 11
Zoom: 10x

----------

Here is the same example in Go font.
![default](https://user-images.githubusercontent.com/33825590/34631807-41204586-f283-11e7-9352-009bdec9fbf4.png)
It looks better.

**Comment by nizarsq** [comment] 2020-07-15 05:05
Can't reproduce the issue reported. Closing the bug for now, if issue still reproducible on the current NotoSans please reopen. The latest font build can be found in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans

**Closed by nizarsq** 2020-07-15 05:05 UTC
Labels: Script-LatinGreekCyrillic
