### ISSUE TITLE
 Noto Nastaliq Urdu: Incorrect rendering of U+0634

### ISSUE THREAD

**Issue by matrixgram-zz** [googlefonts/noto-fonts#1773] opened 2020-06-20 16:12 UTC
#1646 
# Font 
  'NotoNastaliqUrdu-Regular.ttf'
  >   Site: https://www.google.com/get/noto/#Noto%20Nastaliq%20Urdu

### Issue
bad rendering for third character.

### Screenshot
```shell
hb-view NotoNastaliqUrdu-Regular.ttf -u "U+0634;U+0634;U+0634;U+0634;U+0634;"
```
![5sh](https://user-images.githubusercontent.com/27680519/85206413-44f98d80-b337-11ea-92c0-6b3faf8f303d.png)
```shell
hb-view NotoNastaliqUrdu-Regular.ttf -u "U+0634;U+0634;U+0634;U+0634;U+0634;U+0634;"
```
![6sh](https://user-images.githubusercontent.com/27680519/85206417-46c35100-b337-11ea-960f-eb84af677a91.png)
```shell
hb-shape NotoNastaliqUrdu-Regular.ttf -u "U+0634;U+0634;U+0634;U+0634;U+0634;U+0634;"

[ThreeDotsUpAboveNS=5@1753,-149+0|SeenFin=5+2131|ThreeDotsUpAboveNS=4@481,18+0|SeenMed.SWinAoutT2=4@0,932+248|ThreeDotsUpAboveNS=3@1404,477+0|SeenMed.inT2outD1=3@0,997+1838|ThreeDotsUpAboveNS=2@567,652+0|SeenMed.SWinBoutT2=2@0,1514+266|Th
reeDotsUpAboveNS=1@567,720+0|SeenMed.SWinBoutT2=1@0,1582+266|ThreeDotsUpAboveNS=0@1408,1146+0|sp0=0+0|SeenIni.outD1=0@0,1650+1978]
```

**Comment by nizarsq** [comment] 2020-08-26 18:05
@matrixgram-zz could you try the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf. I was not able to reproduce the issue on Chrome or Safari. Thanks

<img width="888" alt="Screen Shot 2020-08-26 at 10 58 22 AM" src="https://user-images.githubusercontent.com/22158882/91339250-1068de80-e78b-11ea-8c4d-bc1ebcc6f3a8.png">
<img width="898" alt="Screen Shot 2020-08-26 at 11 03 51 AM" src="https://user-images.githubusercontent.com/22158882/91339798-d51adf80-e78b-11ea-9a05-098a7aa3ce73.png">

**Comment by nizarsq** [comment] 2020-08-26 19:00
I take my previous comment back, I tried 5 times U+0634 instead of 6 times U+0634. With 6 times U+0634 I can see the behavior reported. This behavior also applies to U+0633 (س) . The question now, Is this combination really valid in real words?
<img width="1365" alt="Screen Shot 2020-08-26 at 11 53 49 AM" src="https://user-images.githubusercontent.com/22158882/91344460-d13e8b80-e792-11ea-92a9-1eb619191de3.png">

**Comment by marekjez86** [comment] 2020-08-26 20:32
@matrixgram-zz : is this actually appearing in the real world? If not I'll close it.

**Comment by simoncozens** [comment] 2022-01-27 08:42
This appears to have been fixed, although the related issue has not.

**Closed by simoncozens** 2022-01-27 08:42 UTC
Labels: Script-Urdu, Script-Nastaliq, in-evaluation
