### ISSUE TITLE
 The Kasra under Fah is not placed properly.

### ISSUE THREAD

**Issue by aliawa** [googlefonts/noto-fonts#767] opened 2016-10-13 06:47 UTC
For example see the attached screen shot. It is properly placed for Lam but for Fah it is merged with the letter rather than being placed under it. "Screenshot_2.png" shows the correct placement of kasra with Fah.
![screenshot_2](https://cloud.githubusercontent.com/assets/6569928/19339117/3901224a-90d6-11e6-9f33-b058650f671a.png)

![screenshot](https://cloud.githubusercontent.com/assets/6569928/19339013/9f908740-90d5-11e6-89dc-7dc6093b0950.png)

**Comment by TidharC** [comment] 2016-10-14 01:25
aliawa@,

Which OS and app are you using?  My results are rather different from yours, using TextEdit on MacOS 10.11.6: the placement of Kasra only looks wrong under the Lam for the UI version of Noto Naskh Arabic.
![notonaskharabickasra](https://cloud.githubusercontent.com/assets/16353803/19372611/6940484a-9172-11e6-9f7a-262d4e7d4c66.png)

**Comment by jungshik** [comment] 2016-10-17 22:55
@TidharC  The placement of Kasra in Noto Naskh UI may be intentional to put the whole glyph within the vertical constraint of UI fonts. 

BTW, please make sure to test with hb-shape as well.   ( @KatMomoi )

@roozbehp @kmansourMT

**Comment by khaledhosny** [comment] 2016-12-26 10:47
The position in the screenshot can’t be intentional, however I can’t reproduce it.

**Comment by roozbehp** [comment] 2016-12-27 19:27
The Kasra under Lam in @TidharC's screenshot is OK. It's to make sure things fit right.

The original issue (under initial Feh) may be due to an old version of the font, or buggy software. Someone should test on Android etc.

**Comment by marekjez86** [comment] 2016-12-27 20:18
@nizarsq : could you check Kasra under initial Feh on an Android device/system?

**Comment by nizarsq** [comment] 2016-12-27 20:33
Kasra under initial Feh on Android device looks Ok. Thank you

![kasra under initial feh](https://cloud.githubusercontent.com/assets/22158882/21507827/8a406252-cc30-11e6-854e-4ed8c3419390.png)

**Comment by marekjez86** [comment] 2016-12-27 21:25
@nizarsq : thank you.
@aliawa : I'll assign this to myself before I'll check with the newest version of Arabic fonts. If I cannot reproduce it, I'll close it. BTW, while get/noto might have not the current version of the fonts, our github site at https://github.com/googlei18n/noto-fonts will always have the most recent, tested versions of the Noto fonts.

**Comment by marekjez86** [comment] 2017-04-11 10:51
@aliawa, @nizarsq : I realized that I do not know how to create the text for this. Could you paste the text sample here? Thank you.

**Comment by nizarsq** [comment] 2017-04-11 15:22
فِي فِو فِا

**Comment by nizarsq** [comment] 2020-06-03 05:48
Retested this issue and the Kasra placed correctly for NotoNaskhArabicUI and NotoNaskhArabic . Closing the bug for now.
<img width="1030" alt="Screen Shot 2020-06-02 at 10 42 12 PM" src="https://user-images.githubusercontent.com/22158882/83600280-156b1880-a523-11ea-9d42-645a8fd16360.png">
<img width="960" alt="Screen Shot 2020-06-02 at 10 42 20 PM" src="https://user-images.githubusercontent.com/22158882/83600332-329fe700-a523-11ea-8082-7c37e5617a81.png">

**Closed by nizarsq** 2020-06-03 05:48 UTC
Labels: Script-Arabic
