### ISSUE TITLE
Missing more syllable like ligatures from Noto Sans Old Hungarian font, and there are non-historic ligatures

### ISSUE THREAD

**Issue by ghost** [googlefonts/noto-fonts#1930] opened 2020-12-06 11:31 UTC
## Defect Report
From "Noto Sans Old Hungarian Font" version  2.00.2 missing more syllable like ligatures, most of them have own meanings. https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
Mainly missing ligatures:
"ád" means "give"  (old form of "ad")
"ál" with joined another word means "false" ("álszakáll")
"hó" means "snow"
"lé" means "liquid", slang: "money", (but "halászlé" means "fish soup" - "halász" : "fisherman" )
"ló" means "horse"
"ró" means "wood with knife mark carving" or "wood with knife carving Old Hungarian letter"
"sí" means "ski"
"só" means "salt"
"úr" means "Lord"
"él" means "he/she lives"
"(disznó)ól" means "pigsty" ("disznó":"pig")
"ár" means "price" (but "ár"+"víz" - "árvíz" = "flood" ,"víz" : "water")
The list is not exhaustive!

Several form of these ligatures:
![rovoteszt](https://user-images.githubusercontent.com/75157441/101278316-ceecc400-37ba-11eb-8e09-5f9134da8fcc.jpg)

There are several non-historical ligatures like "qu", "w", "x", "y" - you can activate with Old Hungarian letters "k" + ZWJ + "V",
"v" + ZWJ + "v", "k" + ZWJ + "sz", "j" + "i". these are replaceable with letters and letter sequences:
"qu" (id in font source: uni10CD3_10CEE) with simple, non-ligature "k" +"v".
"w" (id in font source: uni10CEE_10CEE) with simple "v"
"x" (id in font source: uni10CD3_10CE5) with simple, non-ligature "k" + "sz"
"y" (id in font source: uni10CD0_10CD2) with simple letter "i" or "j", depending on the words. It still can made spelling problem, too, because of that, this "ligature" could be generated automatically. 
These rules widely used rules for replacing foreign letters "qu", "w", "x", and "y"
Non-Historic letters must be remove, because it uses small groups only.

The "qu", "w" and "x" aren't defined in "dlig" section, so these couldn't be generated automatically, don't make spelling problems. 
This "ligatures" in terms of spelling, if we were to accept them, wouldn't be made spelling problems, borrowed only from terms of Latin-based Hungarian spelling.
By terms of spelling Old Hungarian texts' these non-historic "letters" aren't allowed.

**Comment by acszoltan** [comment] 2020-12-07 09:26
@marekjez86 Marek, may I list all of missing syllable-like ligatures, or ignore this issue, because of that, several facts I agree with @Kixidevel

**Comment by tamasbartos** [comment] 2020-12-11 11:09
Correct translation of "ró" :"he/she cuts an Ol Hungarian text on a wooden stick with a knife" or "he/she cuts a sign on a wooden stick with a knife"

**Comment by tamasbartos** [comment] 2020-12-11 11:13
@marekjez86 May I complete the syllable like ligature list, or try to resolve this issue.

**Comment by tamasbartos** [comment] 2020-12-11 11:17
Sorry, I omitted a letter: "he/she cuts an Old Hungarian text on a wooden stick with a knife" is the correct.

**Comment by tamasbartos** [comment] 2020-12-11 11:20
@marekjez86 I think it might be start a new font version, isn't it?

**Comment by tamasbartos** [comment] 2020-12-16 17:50
@marekjez86 
There are already given ligatures:
![Given ligatures, meanings and critics. 1st part](https://user-images.githubusercontent.com/75836867/102386174-0c2d2f00-3fcf-11eb-8c93-1d9fed309f95.jpg)
![Given ligatures, meanings and critics. 2nd part](https://user-images.githubusercontent.com/75836867/102386275-2961fd80-3fcf-11eb-8f5c-d44308523ca1.jpg)
![Given ligatures, meanings and critics. 3rd part](https://user-images.githubusercontent.com/75836867/102386338-40085480-3fcf-11eb-91c4-2959c8199885.jpg)


I collected a list of two-letter syllables with meanings, those would be useful as ligatures:
"az"= "that" or "the" ; "ács" = "carpenter" ; "ág" : "branch" ; "ágy" = "bed" ; "ál" = with joined other words: "false" ;  "ás" = "he/she digs" ; "ász" = "ace"; "át" = "over" ; "eb" = "hound" or "dog" (another form of word "kutya") ; "ez" = "this"; "te" = "you" (singular);
"ér" = "it worths" ; "ég" = "heaven" or "sky" or "it burns";  "éj" = "night" ; "ék" = "wedge" ; "él" = "he/she lives"; "én" = "me" or "I";
"ép" = "intact" ; "és" = "and" ; "ész" = "mind" ; "év" = "year" ;
"is" = "too" ; "ily" (short form of "ilyen") =  "such" ;
"mi" ="we"" 
"így" = "on this way"; "íj" = "bow"; "ín" ="tendon" ;  "íny" = "palate" ; " ív" = "arc"; "íz" = "taste", "sí" = "ski";
"ok" = "reason"; "oly" (short form of "olyan") = "that like"; 

I continue tomorrow....

**Comment by tamasbartos** [comment] 2020-12-17 03:23
@marekjez86  First I prepare the problems and add the collected syllables. After these steps I continue the list.

**Comment by tamasbartos** [comment] 2021-01-19 18:58
Issue #1985 has similar problems as this issue. Can be improved together.

**Comment by rovasinfo** [comment] 2021-04-02 17:20
It is incredible, that how the Unicode standard is misunderstood... ZWJ gives options to create any ligatures, this is why there are NOT in the standard. Therefore it is absolutely unprofessional to state that if there is no ligature in the Unicode standard, do not develop any ligatures in the actual font.
The statement "Compliance with the standard is achieved if its requirements apply without change." is irrelevant, because creating ligatures based on standardized codepoints are not against any standard.
There are more than 100 ligature option, but these ligatures must meet the rules of creating ligatures (not the rules of any standard) as @tamasbartos clearly stated. Please ignore @robihorvath statements and false conclusions.

**Comment by tamasbartos** [comment] 2021-04-02 18:44
Hi, @rovasinfo = Tamás Rumi!
What's your problem really? The additional syllable like ligatures, or you want wrong formed ligatures, or just you want your favourite "ij" and "vv" ligatures, that you and your friends use as "w" and "y" in your books? In Old Hungarian script - or Sekler-rovas script - never was used "x" "q" "y" and "w" LETTERS, until you started using these in your first book in 2008!

**Comment by tamasbartos** [comment] 2021-04-02 18:49
If you will allow me, I will also work on fonts, with and without ligatures!

**Comment by tamasbartos** [comment] 2021-04-02 18:57
@rovasinfo = Tamás Rumi! Or you want  clear ligatureless fonts? I could agree with it.
What about diacritics? Do you agree with them? We hardly not. If you don't agree with diacritics, please comment that issue, too!

**Comment by rovasinfo** [comment] 2021-04-02 19:02
Dear @tamasbartos, I really appreciate your effort to create fonts for rovas. If you need proofs of use of certain  characters, you can check them. However, the most important feature should be the the compatibility of the current Hungarian alphabet, which alsoc contains dz, dzs, w,x,q,y. Other historical or any ligatures are welcomed. This is a living script.

**Comment by rovasinfo** [comment] 2021-04-02 19:06
Letter x is at least 400 years old. https://hu.m.wikipedia.org/wiki/X_(rov%C3%A1s)

**Comment by rovasinfo** [comment] 2021-04-02 19:18
Dz and Dzs are created as ligature after officially adopting these sounds into the latin based Hungarian alphabet. These ligatures followed the change of the alphabeth as early as in 1935. https://hu.m.wikipedia.org/wiki/DZ_(rov%C3%A1s)

**Comment by tamasbartos** [comment] 2021-04-02 19:32
> Dz and Dzs are created as ligature after officially adopting these sounds into the latin based Hungarian alphabet. These ligatures followed the change of the alphabeth as early as in 1935. https://hu.m.wikipedia.org/wiki/DZ_(rov%C3%A1s)

You write this by refferring  to your own page from your own wikipedia article.

**Comment by tamasbartos** [comment] 2021-04-02 20:41
@rovasinfo = Tamás Rumi!  Please read issue #2021 . Impossible to use one ligature activation method (lettercombination) for two meanings and two form. It would be a substandard to use "v"+ZWJ + "v" as "w ligature", the correct using of this combination "vv" (ligature of two "v")

**Comment by rovasinfo** [comment] 2021-04-02 20:44
Exactly. To save copypaste. These facts are facts, you can do the same research work. If you are not familiar or you do not use this script, you have to ask professionals, not amateurs.

**Comment by tamasbartos** [comment] 2021-04-03 05:56
> Letter x, q, y are at least 400 years old. https://hu.m.wikipedia.org/wiki/X_(rov%C3%A1s)
> Letter w is from 1927. https://hu.m.wikipedia.org/wiki/W_(rov%C3%A1s)

These letters aren't 400 years old in Old Hungarian script.. Or do you know "400 old Hungarian word" used, for example, with letter "x"?
These your facts only.
And what about Kazar letters. Do you want include those as ligatures, too?

**Comment by rovasinfo** [comment] 2021-04-03 06:31
@tamasbartos, are you really blind to the reality? Do you know who speaks about Kazar letters? (For outsiders: it is a hidden antisemitism). This forum is about to design fonts, I would keep the track on the contemporary use of the Hungarian rovas, so please stop arguing against letters which can be created by ligatures, even they do not have codepoints, but they have history and needed in order to connect the current Hungarian latin alphabet. Thanks.

**Comment by tamasbartos** [comment] 2021-04-03 06:32
> Exactly. To save copypaste. These facts are facts, you can do the same research work. If you are not familiar or you do not use this script, you have to ask professionals, not amateurs.

Are you historian? I don't think. You are an engineer. Old Hungarian script was phonetic script, as you know. Y replaceable to I or J letters. 
And what about editors, phone devices, which don't use ligatures? Ligature "w" will be appeared as two "v", ligature "y" will be appeared "ij" letters.
That's an another problem! (The iPhone already can appear Old Hungarian letters)

**Comment by rovasinfo** [comment] 2021-04-03 06:36
Concerning letters Dz and Dzs. They are not equal to the combination of D+Z, or D+ZS. They represent different sounds. Example: 'kádzománc' and 'madzag' pronounced differently.

**Comment by rovasinfo** [comment] 2021-04-03 06:45
> > Exactly. To save copypaste. These facts are facts, you can do the same 
> 
> Are you historian? I don't think. You are an engineer. Old Hungarian script was phonetic script, as you know. Y replaceable to I or J letters.
> And what about editors, phone devices, which don't use ligatures? Ligature "w" will be appeared as two "v", ligature "y" will be appeared "ij" letters.
> That's an another problem! (The iPhone already can appear Old Hungarian letters)

@tamasbartos I agree with you. We really would not need ligatures if dz, dzs, x, y, w, q would have their own codepoints. Concerning my knowledge, it is not a one man show that you may think, we are working together with historians, linguists etc, but from the engineering side, the most important condition for any rovas font is the compatibility with the latin based Hungarian alphabet.

**Comment by tamasbartos** [comment] 2021-04-03 08:06
> > > Exactly. To save copypaste. These facts are facts, you can do the same
> > 
> > 
> > Are you historian? I don't think. You are an engineer. Old Hungarian script was phonetic script, as you know. Y replaceable to I or J letters.
> > And what about editors, phone devices, which don't use ligatures? Ligature "w" will be appeared as two "v", ligature "y" will be appeared "ij" letters.
> > That's an another problem! (The iPhone already can appear Old Hungarian letters)
> 
> @tamasbartos I agree with you. We really would not need ligatures if dz, dzs, x, y, w, q would have their own codepoints. Concerning my knowledge, it is not a one man show that you may think, we are working together with historians, linguists etc, but from the engineering side, the most important condition for any rovas font is the compatibility with the latin based Hungarian alphabet.

@rovasinfo Why do you think, that there is a must to make Old Hungarian script compatible with Latin based Hungarian script? Do you think, "cs" letter might be replaceable with "c"+"s"? I know, that it's a stupid example.
Historians of other part think, that Old Hungarian ligature "y" an the others don't required. 
The problem with "y" and "w" ligature is given. That you can not accomplish in the Unicode standard, you try to do with ligatures.
Planning "x", "y", "q" "w", "dz", "dzs" ligatures wasn't a hard work.

**Comment by rovasinfo** [comment] 2021-04-03 09:04
@tamasbartos answers for your questions:
1. Yes, the rovas font MUST be compatible with the CONTEMPORARY latin based Hungarian script. Why? Because it is a living script, not a dead one. The spelling should follow the current grammar, not the grammar used 200 years ago.
2. Cs letter has its own codepoint, thereforr no ligation required.
3. Dzs, dz, q, x, y, w are required for database processes as well. The standard is not complete, and does not consider this script as living. The name of the script means dead script. 
4. So we can override this problem by generating ligatures in the font. It is your task.
5. Planning ligatures maybe not hard work but it should not be adressed to me, but inventors from last century. None of the ligatures were designed by me or our community.
6. Designing a font is not a big task. Easy, if you know the user community needs. You certeanly do not know, please try to write more than one page. We did that, and we have a lot of experience creating rovas texts for publishing books. 98% of rovasbooks are published by the Rovas Foundation. Even we can assist to font developers to design the glyphs as well, following typographic consideretions.

**Comment by rovasinfo** [comment] 2021-04-03 09:26
Please read the NOTO slogan, before you create font which is not fitting to the contemporary living Hungarian grammar and latin based script: font for all the world's languages. 
![image](https://user-images.githubusercontent.com/81823602/113474262-4da6f480-946f-11eb-8151-ae4d2ede84cb.png)

**Comment by tamasbartos** [comment] 2021-04-03 09:28
@rovasinfo You wrote before, that "q","x","y" are 400 years old letters in the Old Hungarian script , which is a lie!
How we can believe, that you and your colleauges are professionals?
You write, that these ligatures are needed, because you and your friends use.
Don't forget the "y" to "ij" and "w" to "vv" ligatureproblems, please!

**Comment by tamasbartos** [comment] 2021-04-03 10:05
> Please read the NOTO slogan, before you create font which is not fitting to the contemporary living Hungarian grammar and latin based script: font for all the world's languages.
> ![image](https://user-images.githubusercontent.com/81823602/113474262-4da6f480-946f-11eb-8151-ae4d2ede84cb.png)

Please read what NoTo means! No tofu! Do you know what tofu means?
Your comment doesn't resolve "y" to "ij" and "w" to two "v" conversion problem with non-ligature capable editors and iPhone.
These problems will be given forever!

**Comment by tamasbartos** [comment] 2021-04-03 10:14
@rovasinfo That's all right, if you really want those ligatures, I might to remove "therre are non-historic ligatures", if you protest against issue #1374 ! ( Missing Old Hungarian diacritics)

**Comment by rovasinfo** [comment] 2021-04-03 10:17
> @rovasinfo You wrote before, that "q","x","y" are 400 years old letters in the Old Hungarian script , which is a lie!
Please moderate yourself, and read carefully: "q","x","y" are 400 hundreds years old, w is created around 1930
> How we can believe, that you and your colleauges are professionals?
Do not believe, study and read about this topic, before commenting. 
> You write, that these ligatures are needed, because you and your friends use.
The ligatures are existing, and we use them. "your friends" means our readers. Please select your words again.
> Don't forget the "y" to "ij" and "w" to "vv" ligatureproblems, please!
I never forget your Y and W problem. 
**Solution one:** ask Unicode to give a codepoint. especially for DZ and DZS, because these represent different sounds. 
**Solution two:** use non-used areas (like PUA) 
W: capital U+10CB6 small: U+10CF6
Y: capital U+10CB8 small: U+10CF8

I do not think that it is our problem to give solution for a situation caused by wrongly encoded script standard, where we spoke about this problem, in 2008. Of course, if you can solve the problem by using special solution, that would be great, for example, using 3 v to represent W ligature (v+ZWJ+v+ZWJ+v).

**Comment by tamasbartos** [comment] 2021-04-03 10:30
> > @rovasinfo You wrote before, that "q","x","y" are 400 years old letters in the Old Hungarian script , which is a lie!
> > Please moderate yourself, and read carefully: "q","x","y" are 400 hundreds years old, w is created around 1930
> > How we can believe, that you and your colleauges are professionals?
> > Do not believe, study and read about this topic, before commenting.
> > You write, that these ligatures are needed, because you and your friends use.
> > The ligatures are existing, and we use them. "your friends" means our readers. Please select your words again.
> > Don't forget the "y" to "ij" and "w" to "vv" ligatureproblems, please!
> > I never forget your Y and W problem.
> > **Solution one:** ask Unicode to give a codepoint. especially for DZ and DZS, because these represent different sounds.
> > **Solution two:** use non-used areas (like PUA)
> > W: capital U+10CB6 small: U+10CF6
> > Y: capital U+10CB8 small: U+10CF8
> 
> I do not think that it is our problem to give solution for a situation caused by wrongly encoded script standard, where we spoke about this problem, in 2008. Of course, if you can solve the problem by using special solution, that would be great, for example, using 3 v to represent W ligature (v+ZWJ+v+ZWJ+v).

The ligatures doesn't require direct codepoints, but your idea might be good.
So please protest against issue #1374 ! It's about using accents or duplication marks in Old Hungarian script.

@marekjez86 As I know, the Unicode codepoints, which aren't defined by Unicode, the Noto doesn't owerride. Ligatures might be used just lettercombinations. I know well?

**Comment by tamasbartos** [comment] 2021-04-03 10:36
@marekjez86  I don't know that, you got the previous quick reply for @rovasinfo. If not, please read it in issue #1930 and answer, please.

**Comment by tamasbartos** [comment] 2021-04-03 11:19
@rovasinfo We must to wait answer of @marekjez86 , he is the leader of the project.. As I know he doesn't work at weekend.

**Comment by rovasinfo** [comment] 2021-04-03 12:08
@tamasbartos wrote: @rovasinfo That's all right, if you really want those ligatures, I might to remove "therre are non-historic ligatures", if you protest against issue #1374 ! ( Missing Old Hungarian diacritics)

I protested against the accutes. as you requested, I hope you will support the so called non-historic ligatures which are still existing. Thanks. If you ask Andras Tisza, you know very well him, he also open to use these characters silently.

**Comment by tamasbartos** [comment] 2021-04-03 12:28
@rovasinfo Ups! Not I opened this issue, I must ask @marekjez86 ." Ghost" means, that the user clear himself from the github.com. 
@marekjez86 If you can, remove this issues caption the text "and there are non historic ligatures" or close it, and I will open "Missing syllable like ligatures from Noto Sans Old Hungarian font”

**Comment by tamasbartos** [comment] 2021-04-04 09:40
@marekjez86  Marek! @rovasinfo  would like to associate Old Hungarian capital "W" to u+10CB6, small "w" to u+10CF6, capital "Y" to u+10CB8, small "y" to u+10CF8. If it possible, problems of the "y" and "w" ligatures would be resolved. In that case please remove "and there are non-historic ligatures" text from  this issue's caption!
And he would like that the noto-fonts project asks Unicode to give codepoints for letter "dz" and "dzs".

**Comment by rovasinfo** [comment] 2021-04-04 17:08
> @marekjez86 Marek! @rovasinfo would like to associate Old Hungarian capital "W" to u+10CB6, small "w" to u+10CF6, capital "Y" to u+10CB8, small "y" to u+10CF8. If it possible, problems of the "y" and "w" ligatures would be resolved. In that case please remove "and there are non-historic ligatures" text from this issue's caption!
> And he would like that the noto-fonts project asks Unicode to give codepoints for letter "dz" and "dzs".

Thanks for supporting these letters. For DZ and DZS we use these (still empty) codepoints:
U+10CB3 CAPITAL LETTER DZ
U+10CF3 SMALL LETTER DZ
U+10CB4 CAPITAL LETTER DZS
U+10CF4 SMALL LETTER DZS

**Closed** 2021-04-12 19:36 UTC
Labels: Script-OldHungarian
