### ISSUE TITLE
Character collision in Noto Serif Kannada

### ISSUE THREAD

**Issue by Etewilak** [googlefonts/noto-fonts#2299] opened 2022-03-18 12:54 UTC
When the sequence U+0CB7 U+0CCD U+0C9F U+0CCD U+0CB0 is entered, U+0CB0 clashes with U+0C9F:
![image](https://user-images.githubusercontent.com/55674356/159006039-9035de68-3ed5-4141-9ee5-870ea09d7636.png)
When the sequence U+0CB8 U+0CCD U+0CA4 U+0CCD U+0CB0 is entered, U+0CB0 clashes with U+0CA4:
![image](https://user-images.githubusercontent.com/55674356/159006391-0fa312eb-02eb-404f-83f3-7a200156ff7d.png)

**Comment by sridatta1** [comment] 2022-03-18 17:28
Duplicate of #2152.
It can tested wih the fonts downloaded from https://fonts.google.com/download?family=Noto%20Serif%20Kannada

**Comment by simoncozens** [comment] 2022-03-18 18:59
Yes, this is fixed in the repo. New versions will need to be onboarded to Google Fonts, but that’s part of a bigger process I’m looking at.

**Closed** 2022-04-15 21:32 UTC
Labels: Script-Kannada
