### ISSUE TITLE
Extra diacritics on Arabic word ligatures

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1200] opened 2018-05-29 17:49 UTC
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
In Noto Sans Arabic, the ligature for Allah and the discretionary ligature for Muhammad insert diacritics not present in the text. If the text does include diacritics, the rendering includes both the real diacritics and the ligatures’ figments.

### Character data
اللّٰه
U+0627 ARABIC LETTER ALEF
U+0644 ARABIC LETTER LAM
U+0644 ARABIC LETTER LAM
U+0651 ARABIC SHADDA
U+0670 ARABIC LETTER SUPERSCRIPT ALEF
U+0647 ARABIC LETTER HEH
مُحَمَّد
U+0645 ARABIC LETTER MEEM
U+064F ARABIC DAMMA
U+062D ARABIC LETTER HAH
U+064E ARABIC FATHA
U+0645 ARABIC LETTER MEEM
U+064E ARABIC FATHA
U+0651 ARABIC SHADDA
U+062F ARABIC LETTER DAL

### Screenshot
![اللّٰه](https://user-images.githubusercontent.com/1124347/40674684-8c9c94de-6343-11e8-8495-68f4ffe68a41.png)
![مُحَمَّد](https://user-images.githubusercontent.com/1124347/40674685-8cb9ed5e-6343-11e8-9923-7f6504b0ed79.png)

**Comment by nizarsq** [comment] 2018-07-09 21:51
https://github.com/googlei18n/noto-fonts/issues/836

**Comment by nizarsq** [comment] 2020-05-22 19:58
This extra diacritics issue fixed. There is another issue observed but it's unrelated to this specific issue. closing as fixed.
<img width="479" alt="Screen Shot 2020-05-22 at 12 53 58 PM" src="https://user-images.githubusercontent.com/22158882/82705084-ca502c00-9c2b-11ea-805a-0728f6358631.png">

**Comment by dscorbett** [comment] 2020-12-25 15:33
This bug is back for “مُحَمَّد” in [version 2.005](https://github.com/googlefonts/noto-fonts/blob/3599b1bb31ae94e7091f270b60c5f7c1c00f8ad5/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf).

**Comment by nizarsq** [comment] 2020-12-25 19:33
Not able to reproduce the issue with the mentioned combination "0645 064F 062D 064E 0645 064E 0651 062F" مُحَمَّد. 
I don't recall any work done recently in this area.

<img width="1174" alt="Screen Shot 2020-12-25 at 11 26 36 AM" src="https://user-images.githubusercontent.com/22158882/103141073-0fe24500-46a4-11eb-9fc6-49ea1e8ef90a.png">
<img width="870" alt="Screen Shot 2020-12-25 at 11 26 56 AM" src="https://user-images.githubusercontent.com/22158882/103141081-1a9cda00-46a4-11eb-83ec-55b4b9b54cb9.png">

<img width="567" alt="Screen Shot 2020-12-25 at 11 18 24 AM" src="https://user-images.githubusercontent.com/22158882/103140996-e83ead00-46a2-11eb-8e74-deba14396b79.png">

**Comment by dscorbett** [comment] 2020-12-25 20:03
It’s a discretionary ligature. You need to enabled 'dlig' to test it.

**Comment by nizarsq** [comment] 2020-12-25 20:30
Will work on dlig issues sometime soon. Thanks

**Closed** 2021-01-06 01:44 UTC
Labels: Monotype, Script-Arabic, Status-Duplicate
