### ISSUE TITLE
The Glyphs of \ua84d and \ua84e have been error reversed

### ISSUE THREAD

**Issue by Lo-Dyih-Yuaan** [googlefonts/noto-fonts#1274] opened 2018-08-30 18:33 UTC
### Title 
The Glyphs of \ua84d and \ua84e been error reversed

### Font 
NotoSansPhagsPa-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansPhagsPa/NotoSansPhagsPa-Regular.otf
Date: 2018-8-30

### Font Version
2.000

### Issue
If you compare the font with the glyphs in https://www.unicode.org/charts/PDF/UA840.pdf, you will find the problem.

**Comment by marekjez86** [comment] 2018-09-01 02:34
[NotoSansPhagsPa-Regular.ttf.zip](https://github.com/googlei18n/noto-fonts/files/2341998/NotoSansPhagsPa-Regular.ttf.zip)

@Lo-Dyih-Yuaan : could you check the font in the above zip file? i think the problem should be fixed

**Comment by simoncozens** [comment] 2022-04-18 12:48
This is a duplicate of #1348.

**Closed by simoncozens** 2022-04-18 12:48 UTC
Labels: Script-Phagspa
