### ISSUE TITLE
Noto Sans Mono 'r' glyph has serifs

### ISSUE THREAD

**Issue by ataraxia937** [googlefonts/noto-fonts#1126] opened 2018-04-04 23:21 UTC
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
The lower-case 'r' glyph in the new Noto Sans Mono has large serifs. None of the other Latin letters have them.

### Font 
NotoSansMono-Regular.ttf:

### Where the font came from, and when
Arch Linux distribution
Date: 2018-04-04

### Font Version
131072
  
### OS name and version
Arch Linux (current)

### Issue
The lower-case 'r' glyph in the new Noto Sans Mono has large serifs - a bar across the bottom and an extension to the left from the top of the letter. None of the other Latin letters have similar elements.
The same glyph in Noto Sans is much more appealing.

**Comment by horrovac** [comment] 2018-04-05 09:14
Confirm.
Also the fonts are higher than Noto Mono, they appear as if there was increased line spacing. With Noto Mono and pixelsize=8 my terminals used to be 484x244, now they're 484x292. The lines are 2 pixels higher.

**Comment by joshuakraemer** [comment] 2018-12-10 21:40
I agree. Please revert to the old 'r' glyph without serifs. It better matches the other sans-serif glyphs and I think it's more legible (especially in smaller sizes).

**Comment by aphirst** [comment] 2019-01-04 14:39
Confirmed. the lowercase `r` looks more like a half-height capital `I`, and is generally jarring to look at and difficult to quickly parse.

**Comment by luaraneda** [comment] 2019-09-16 16:10
Is this being addressed? I'm trying to use noto as a terminal font, but the serifs makes the "r" glyph too similar to the "I" one.

#1253 and #1136 don't have any movement either.

NotoMono is not longer available, as #1029 removed it.

Can we at least have an ETA when this will be fixed?

![image](https://user-images.githubusercontent.com/8550628/64974438-369bb400-d883-11e9-8d8a-5d25acefa0b3.png)

**Comment by nizarsq** [comment] 2020-07-08 15:41
This issue still reproducible in the current font version https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
<img width="603" alt="Screen Shot 2020-07-08 at 8 41 18 AM" src="https://user-images.githubusercontent.com/22158882/86939727-cbafb800-c0f6-11ea-8da1-d153695579c4.png">

**Comment by marekjez86** [comment] 2020-07-26 19:15
Design decision. Will not be changed.

**Closed by marekjez86** 2020-07-26 19:15 UTC
Labels: Script-LatinGreekCyrillic, Script-Monospace, in-evaluation

**Comment by jonhoo** [comment] 2020-07-26 19:25
I'm confused — it is a design decision to include a letter with a serif in a sans-serif font? Should the font be renamed then? Could you give us some more insight into this design decision?

**Comment by marekjez86** [comment] 2020-07-26 19:36
Thank you for the feedback. We'll drop Sans from the name (to return to the previous name). That was a great idea. Thanks again.

**Comment by moyogo** [comment] 2020-07-26 19:45
@jonhoo It is a common design decision to have serifs on some glyphs in sans serif fonts when it makes sense. For example, the capital i can have serifs to help distinguish it from lowercase l or number 1. In monospace fonts it’s common to have serifs on the i j l to make them wider and better match the width of the other glyphs. For r there’s two possible design decisions, make r wider or give it serifs. Having serifs on a tiny set of glyphs doesn’t make this less of a Sans that Noto Sans.

**Comment by davelab6** [comment] 2020-07-29 16:25
@jonhoo and @joshuakraemer I broadly agree with @moyogo and explained a little more in https://github.com/googlefonts/noto-fonts/issues/1253#issuecomment-665757225 - the image @joshuakraemer posted here seems to me to illustrate the 'swiss cheese' effect of too-much and uneven whitespace in the `Noto Mono` design, so I am skeptical about reverting to a sans-serif `r` as a default design form. However, if the sans-serif `r` is no longer available, retaining it in a stylistic set seems like an issue that can be addressed; and folks like @luaraneda can then use the new 2020 era noto-build tools to 'freeze' such a feature into the default design if they can't configure their terminal/app to use OpenType features.

@marek and I and Monotype folks discussed this naming issue and I don't feel strongly about it, but MT folks pointed out that family renaming can be disruptive for users. However, it seems `Noto Mono` was the original name, then it was renamed to `Noto Sans Mono` with design changes like the addition of the serifs, and this week Marek has renamed it back to `Noto Mono` :) So, the naming is not super simple. My soft recommendation is to retain the `Noto Sans Mono` name, simply to minimize disruption.

**Comment by anthrotype** [comment] 2020-07-29 16:38
> My soft recommendation is to retain the Noto Sans Mono name, simply to minimize disruption

+1 on keeping the current name to avoid even further confusions

**Comment by marekjez86** [comment] 2020-07-29 17:17
we'll keep the current name... thank you

**Comment by nbruin** [comment] 2022-06-15 18:13
I see that having serifs on 'r' in Noto Sans Mono is considered a design decision. I just ran into it when I found that FireFox on Fedora 36 by default uses the Noto fonts (which for the most part are fine). However, the appearance of a monospace "r" was so jarring to me, and made the string so poorly readable, that I immediately looked for a replacement. DejaVu Sans Mono seems to be working well instead.

I usually stick with default fonts, but the lower case in Noto Sans Mono made me look for an alternative immediately. Alternatives are available, so my problem is solved, but if the objective of Noto Sans Mono is to be a fairly universally acceptable, good screen font for things like web browsers, then it's currently failing that objective.

**Comment by joshuakraemer** [comment] 2022-06-16 09:32
Interestingly, the Berkeley Mono Font had an r with serifs in the preview version (top), but in the final version the serifs are gone (bottom):

![BerkeleyMono](https://user-images.githubusercontent.com/10373011/174025112-383dbd20-2095-4ad2-92ef-2928100353c9.png)

(Source: https://neil.computer/notes/isomatic-typeface-rev-6-wip/, https://berkeleygraphics.com/typefaces/berkeley-mono)

I think the r in a sans-serif monospace font always is a compromise, having either a little bit too much whitespace (without serifs) or looking weird and being less legible (with serifs). A quick search shows that most font designers seem to agree that the first option (without serifs) is the better choice (and I agree as well).

Fonts with sans-serif r: Andale Mono, Consolas, Eureka Mono, Inconsolata, Interstate Mono, Letter Gothic, Liberation Mono, Lucida Sans Typewriter, Monaco, Monospace 821, Prima/DejaVu Sans Mono, Roboto Mono, Segoe Mono, Source Code Pro, Typewriter Gothic, Univers Next Typewriter

Fonts with serif r: Excellent, Fira Mono, Fago Monospaced, Fedra Mono, Nexus Typewriter, SF Mono, TheSans Typewriter

**Comment by joshuakraemer** [comment] 2022-06-16 09:35
Interestingly, the Berkeley Mono typeface had an r with serifs in the preview version (top), but in the final version the serifs are gone (bottom):

![BerkeleyMono](https://user-images.githubusercontent.com/10373011/174025112-383dbd20-2095-4ad2-92ef-2928100353c9.png)

(Source: https://neil.computer/notes/isomatic-typeface-rev-6-wip/, https://berkeleygraphics.com/typefaces/berkeley-mono)

I think the r in a sans-serif monospace font always is a compromise, having either a little bit too much whitespace (without serifs) or looking weird and being less legible (with serifs). A quick search shows that most type designers seem to agree that the first option (without serifs) is the better choice (and I agree as well).

Typefaces with sans-serif r: Andale Mono, Consolas, Eureka Mono, Inconsolata, Interstate Mono, Letter Gothic, Liberation Mono, Lucida Sans Typewriter, Monaco, Monospace 821, Prima/DejaVu Sans Mono, Roboto Mono, Segoe Mono, Source Code Pro, Typewriter Gothic, Univers Next Typewriter

Typefaces with serif r: Excellent, Fira Mono, Fago Monospaced, Fedra Mono, Nexus Typewriter, SF Mono, TheSans Typewriter

**Comment by harjitmoe** [comment] 2022-07-02 11:32
> However, the appearance of a monospace "r" was so jarring to me, and made the string so poorly readable, that I immediately looked for a replacement. […] At normal body text sizes on a 1080 display, the "r" renders in such a way that the stem of the "r" seems to stand right of centre, with way more weight on the serifs on the left than on that arc on the right. It just doesn't look like an "r" under those conditions. 

Agreed, insofar as I found it was looking more like a gamma than an "r".
