### ISSUE TITLE
Misplacement of various combining characters

### ISSUE THREAD

**Issue by Linguistx** [googlefonts/noto-fonts#1986] opened 2021-01-20 04:18 UTC
## Defect Report
Test the following combining characters on 'NotoSerif-Regular.ttf'

a̤ e̤ i̤ o̤ ṳ a̘ e̘ i̘ o̘ u̘ a̟ e̟ i̟ o̟ u̟

This is the result

![misplacment](https://user-images.githubusercontent.com/31242898/105126205-58b9dc00-5b32-11eb-8837-9f204ca3633e.PNG)

These symbols are used in the International Phonetic Alphabet (IPA). I did not test all IPA combining characters on all IPA letters, but this sample makes me think it could be a widespread issue with other combining symbols?

Here are some references for IPA diacritics:

- https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Diacritics_and_prosodic_notation
- https://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm

PS: this font rules for IPA! Keep up the great work

**Comment by dscorbett** [comment] 2021-01-20 14:21
This is a duplicate of issue #1791.

**Comment by moyogo** [comment] 2021-04-10 19:44
Duplicate of #1791.

**Closed by moyogo** 2021-04-10 19:44 UTC
Labels: Script-LatinGreekCyrillic
