### ISSUE TITLE
Noto Kufi Arabic isn't working with PowerPoint

### ISSUE THREAD

**Issue by mdqara** [googlefonts/noto-fonts#1526] opened 2019-06-13 10:55 UTC
### Font 
  > Noto Kufi Arabic'.

### Where the font came from, and when

<img src="https://2.top4top.net/p_1259vetgx1.png">

### OS name and version
  > Windows 10

### Application name and version
  > Microsoft Power Point

### Issue
  > The font "Noto Kufi Arabic" not working while the font "Noto Naskh Arabic" is working on PowerPoint

**Comment by MDCR55** [comment] 2019-10-30 08:49
#1599

**Comment by marekjez86** [comment] 2019-10-30 11:12
@MDCR55 : thank you for the issue report.

Could you help us by

1. uninstall existing Noto Kufi Arabic font(s)
2. download and install the fonts from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoKufiArabic
3. In your powerpoint select all the text you want in NotoKufiArabic 
4. choose NotoKufiArabic as the font for your selection
5. Please let me know how the selected text displays
6. Note that this is a new version of NotoKufiArabic so there might be some new issues present -- it also might or might not fix the problem described here (if it works in Word or Notepad on the same system, but not in PowerPoint, then it might be a PowerPoint problem)

**Comment by MDCR55** [comment] 2019-10-30 13:10
Thians @marekjez86  for your response.
I have tried the new fonts but still the problem exist on PowerPoint only.

Again, I do really appreciate your help

**Comment by nizarsq** [comment] 2020-06-12 03:43
Tested reported issue on Powerpoint 16.0.11929.20392. NotokufiArabic not rendered correctly. I used NotoKufiArabic in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoKufiArabic
![NotokufiArabic-1526](https://user-images.githubusercontent.com/22158882/84462517-1d624100-ac24-11ea-8bb4-60383a45a582.png)

**Comment by marekjez86** [comment] 2020-06-12 05:26
@nizarsq : for Windows only, could you try hinted ttf? you don't need to redo everything with hinted but I'm curious in this case

**Comment by nizarsq** [comment] 2020-06-12 05:52
@marekjez86 I see same behavior for hinted font.
![NotoKufiArabic-hinted-1526](https://user-images.githubusercontent.com/22158882/84469563-3116a300-ac36-11ea-9917-a5a88abd880b.png)

**Comment by marekjez86** [comment] 2020-10-16 01:38
@nizarsq : could you try with the newest hinted one?

**Comment by mdqara** [comment] 2020-10-17 07:28
@marekjez86  the problem still exist with the new [hinted fonts here ](https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoKufiArabic)

![](https://i.imgur.com/Opkwbu9.png)

**Comment by nizarsq** [comment] 2020-11-25 01:03
@marekjez86 For some reason none of attached screenshots above using NotoKufiArabic. For some reason Microsoft powerpoint fallback to another font. I was not able to force it to use Noto Kufi Arabic, it just keep using another font (even it shows Noto Kufi Arabic as the font used). Microsoft office does use NotoKufiArabic and it looks good. 
![Microsoft powerpoint](https://user-images.githubusercontent.com/22158882/100168775-c4efca80-2e76-11eb-84e3-7ce097ae5de5.PNG)
![Microsoft office](https://user-images.githubusercontent.com/22158882/100168780-c7522480-2e76-11eb-8d41-544e32d7acc8.PNG)

**Comment by simoncozens** [comment] 2022-04-27 12:27
Closing as duplicate of #931. If there are any updates, please add them to that issue instead.

**Closed by simoncozens** 2022-04-27 12:27 UTC
Labels: Script-Arabic, Status-Unreproducible, Platform-Windows, app-dependent-behavior
