### ISSUE TITLE
Soyombo: why substitution 25CC + umlaut → umlaut

### ISSUE THREAD

**Issue by Mercury13** [googlefonts/noto-fonts#2159] opened 2021-10-18 19:01 UTC
### Title 
In Soyombo there’s substitution 25CC + umlaut → same umlaut

### Font 
NotoSansSoyombo-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2021-10-18

### Font Version
2.000

### OS name and version
W10 20H2, but probably all OS

### Application name and version
Qt 6.2.0, but probably all apps

### Issue
  1. Type 25CC dotted circle + any umlaut
  2. You see umlaut
  3. You should see umlaut planted on 25CC
  4. Done by ligature substitution w/o any specific OT feature (not liga, not rlig…)

### Character data
U+25CC dotted circle
U+11A51 Soyombo vowel sign I …………… U+11A5B Soyombo vowel Length mark
U+11A8A Soyombo final consonant sign G ……………… U+11A99 Soyombo subjoiner

**Comment by simoncozens** [comment] 2022-02-25 15:29
This is a duplicate of #1724

**Closed by simoncozens** 2022-02-25 15:29 UTC
Labels: Script-Soyombo, dotted-circle
