### ISSUE TITLE
Noto Serif has improperly placed umlauts

### ISSUE THREAD

**Issue by Mercury13** [googlefonts/noto-fonts#2114] opened 2021-07-21 19:50 UTC
### Title 
Several lower and overlay umlauts are badly placed, both on Latin “a” and on dotted circle used for showcasing them.

### Font 
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2021-07-21

### Font Version
2.004

### OS name and version
Windows 10 20H2 (and probably all OS’es)

### Application name and version
Probably all software. Seen in Qt 6.1.2 and LibreWriter 7.1.2.2.

### Issue
  1. Write Latin a, then 0331.
  2. The line is shifted to the right.
  3. The line should be in the middle of the letter.
  4. Works really better than v2.000, but W10 Cambria is right with all these umlauts!

### Character data
0316 Combining grave accent below
0317 Combining acute accent below
0318 Combining left tack below
0319 Combining right tack below
031B Combining horn
031C Combining left half ring below
031D Combining up tack below
031E Combining down tack below
031F Combining plus sign below
0320 Combining minus sign below
0322 Combining retroflex hook below
0324 Combining diaeresis below
0326 Combining comma below
0329 Combining vertical line below
032A Combining bridge below
032B Combining inverted double arch below
032C Combining caron below
032D Combining circumflex accent below
032E Combining breve below
032F Combining inverted breve below
0330 Combining tilde below
0331 Combining macron below
0332 Combining low line
0333 Combining double low line
0334 Combining tilde overlay
0335 Combining short stroke overlay
0336 Combining long stroke overlay
0337 Combining short solidus overlay
0338 Combining long solidus overlay
0339 Combining right half ring below
033A Combining inverted bridge below
033B Combining square below
033C Combining seagull below
0345 Combining Greek ypogegrammeni
0347 Combining equals sign below
0348 Combining double vertical line below
0349 Combining left angle below
034D Combining left right arrow below
034E Combining upwards arrow below
0359 Combining asterisk below
035A Combining double ring below

### Screenshot
Noto Serif
![image](https://user-images.githubusercontent.com/10164882/126550889-1ad52a7e-65b5-4852-a789-deff66d52a26.png)
![image](https://user-images.githubusercontent.com/10164882/126551597-926d7d92-6346-4bb0-ba5c-6d9c47701af9.png)

Cambria
![image](https://user-images.githubusercontent.com/10164882/126551003-4dd0e24d-8cef-4c8a-a45f-68a3f06b5467.png)
![image](https://user-images.githubusercontent.com/10164882/126551782-c7685fd5-7e0f-4deb-a21d-d9ae63f2bc3d.png)

**Comment by Linguistx** [comment] 2021-07-23 23:13
I think this might be a duplicate of https://github.com/googlefonts/noto-fonts/issues/1791

I would love to see this fixed!

**Comment by simoncozens** [comment] 2022-02-25 15:27
Yes, duplicate of #1791. Closing here.

**Closed by simoncozens** 2022-02-25 15:27 UTC
Labels: Script-LatinGreekCyrillic, Serif
