### ISSUE TITLE
Misplaced candrabindu on Bengali anji

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1608] opened 2019-11-04 19:32 UTC
### Font
NotoSerifBengali-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9c74a9735acb66df9a41ad86e58020430ede9a9d/phaseIII_only/hinted/ttf/NotoSerifBengali/NotoSerifBengali-Regular.ttf
Date: 2019-11-04

### Font version
Version 2.000; ttfautohint (v1.8.2)

### Issue
Candrabindu is not properly centered above anji.

### Character data
ঀঁ
U+0980 BENGALI ANJI
U+0981 BENGALI SIGN CANDRABINDU

### Screenshot
![ঀঁ](https://user-images.githubusercontent.com/1124347/68151032-eea61e80-ff0e-11e9-821e-ef48564b158e.png)

**Comment by nizarsq** [comment] 2020-06-11 04:53
Currently looks ok. Closing this bug for now, please reopen if you have other thoughts.
<img width="1129" alt="Screen Shot 2020-06-10 at 9 22 17 PM" src="https://user-images.githubusercontent.com/22158882/84346412-c9445780-ab64-11ea-9201-51e987336a67.png">

**Closed by nizarsq** 2020-06-11 04:53 UTC
Labels: Script-Bengali

**Comment by nizarsq** [comment] 2020-06-11 14:42
Duplicate #604

**Comment by nizarsq** [comment] 2020-06-11 14:43
Duplicate of #604
