### ISSUE TITLE
in Noto Nastaliq font add ٻ ڄ ڊ ݙ ڳ ݨ  ــ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#368] opened 2015-06-08 18:34 UTC
```
What steps will reproduce the problem?
1. in Noto Nastaliq font these seven letters are missing   ٻ ڄ ڊ ݙ ڳ ݨ  
ـ  ـ 
2. Also add 
3.

What is the expected output? What do you see instead?
Noto Nastaliq will support Saraiki.

What version of the product are you using? On what operating system?
wind 7 

Please provide any additional information below.
in Noto Nastaliq font add ٻ ڄ ڊ ݙ ڳ ݨ  ــ . This will support Saraiki.

```

Original issue reported on code.google.com by `mpqa...@gmail.com` on 13 May 2015 at 3:05

**Comment by kmansourMT** [comment] 2015-06-10 00:57
Issue 368 is a duplicate of 372 which was closed/reassigned by Behdad earlier today.

**Comment by marekjez86** [comment] 2020-07-28 21:15
Fixed. Five Siraiki characters added. U+0678 not needed.

**Closed by marekjez86** 2020-07-28 21:15 UTC
Labels: FoundIn-1.x, Script-Urdu, Type-Enhancement
