### ISSUE TITLE
Xiangqi glyphs in Noto Sans Symbols 2 shows incorrectly

### ISSUE THREAD

**Issue by Buernia** [googlefonts/noto-fonts#1911] opened 2020-10-31 05:22 UTC
## Defect Report
Xiangqi glyphs in Noto Sans Symbols 2 shows incorrectly.

### Font 
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts
Date: 2020-10-31

### Font Version
2.003

### Issue
The hanzi in the glyph is incorrectly written as “象” (elephant) in U+1FA6A Xiangqi Black Horse. The correct hanzi is “馬”.
The hanzi in the glyph is incorrectly written as “馬” (horse) in U+1FA6B Xiangqi Black Chariot.  The correct hanzi is “車”.

### Character data
🩪🩫
U+1FA6A Xiangqi Black Horse
U+1FA6B Xiangqi Black Chariot

### Screenshot
![图片](https://user-images.githubusercontent.com/11886946/97772038-eb735c00-1b7d-11eb-80ce-a7c5e18af124.png)

**Comment by nizarsq** [comment] 2020-10-31 05:59
Duplicate of #1691

**Comment by nizarsq** [comment] 2020-10-31 21:29
This issue fixed. Please let me know if they look ok now. Thank you for filing this issue.

**Closed by nizarsq** 2020-10-31 21:29 UTC
Labels: Script-Symbol
