### ISSUE TITLE
"Combining comma above right" character needs spacing

### ISSUE THREAD

**Issue by dlevineBC** [googlefonts/noto-fonts#1478] opened 2019-04-10 20:54 UTC
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
When using the 'combining comma above right' U+0315, the comma squishes into the next character to the right. This is required for the Kwak̓wala language specifically between the characters of k'w, t's, and t'ł

### Font 
NotoSans-Regular.ttf

### OS name and version
Example is shown on Chrome using Mac

### Character data
 t̕s
 U+74 U+315 U+73

### Screenshot
Here is the bug in rendering
<img width="105" alt="ts" src="https://user-images.githubusercontent.com/29607430/55912166-0135c080-5b97-11e9-8baf-1283d2a08fc1.png">

Here is how it is supposed to be rendered
<img width="125" alt="proper-ts" src="https://user-images.githubusercontent.com/29607430/55912369-6093d080-5b97-11e9-9724-59161152cb3b.png">

**Comment by nizarsq** [comment] 2020-07-01 22:05
Look like this issue has been resolved in the current NotoSans. Please use the font in this directory to verify the fix https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
 <img width="448" alt="Screen Shot 2020-07-01 at 3 02 06 PM" src="https://user-images.githubusercontent.com/22158882/86295608-d7a5f200-bbab-11ea-9ad9-c805586df25d.png">

**Closed by nizarsq** 2020-07-01 22:05 UTC
Labels: Script-LatinGreekCyrillic

**Comment by moyogo** [comment] 2020-07-02 08:59
@nizarsq the test string in the screenshots seems to be "k'w, t's, and t'ł" (with U+0027) instead of "k̕w, t̕s, and t̕ł" (with U+0315). @dlevineBC had provided "t̕s"  U+74 U+315 U+73 in the character data but mentioned "k'w, t's, and t'ł" (with U+0027) in the issue title. That said the issue is fixed indeed.

**Comment by nizarsq** [comment] 2020-07-02 14:38
@moyogo Thank you for the correction. Apparently I used the characters set @dlevineBC provided. I was not expecting to see (U+0027) APOSTROPHE when the issue is with U+0315 (COMMA). The good thing this issue has been resolved.

**Comment by nizarsq** [comment] 2020-07-02 14:39
<img width="566" alt="Screen Shot 2020-07-02 at 7 39 09 AM" src="https://user-images.githubusercontent.com/22158882/86372518-1fbe2680-bc37-11ea-8360-9c585754bd59.png">
