### ISSUE TITLE
Noto Naskh Arabic crashes Pages for Mac when typing الله

### ISSUE THREAD

**Issue by dakaplo** [googlefonts/noto-fonts#839] opened 2017-02-15 04:08 UTC
I noticed that Noto Naskh Arabic has trouble with the الله ligature, at least in Pages on Mac (OSX 10.12.1). Typing the word crashed the program, as did having it typed in one font, and then trying to change fonts to Noto Naskh Arabic. I was hoping the screenshot would capture the spinning-wheel of the mouse, but you can at least see that the font selection menu is stuck in gray. This is the point when Pages became unresponsive and I had to Force Quit.

<img width="1036" alt="screen shot 2017-02-14 at 11 04 09 pm" src="https://cloud.githubusercontent.com/assets/12958312/22960251/413a9dba-f30a-11e6-933b-ce67e4826def.png">

**Comment by punchcutter** [comment] 2017-02-15 04:46
I can't get it to crash for me, but I'm sure I also have different versions of everything. I tried with
Pages 5.6.2 (2573) on OS X 10.11.6 and also with Pages 6.0.5 (4052) on OS X 10.12.4 Beta (16E154a). I used the Noto Naskh Arabic from the hinted folder. I typed the ligature using each of the built in Arabic keyboards and also tried switching fonts like you said.

**Comment by marekjez86** [comment] 2017-02-15 06:39
MacOSX 10.12.3; Pages  6.0.5 (4052); unhinted Noto Naskh Arabic

I'm unable to reproduce the crash but I pasted the الله ligature (don't know how to type Arabic)

**Comment by jungshik** [comment] 2017-02-15 20:17
Could be a bug in a certain combination of Pages + Mac OS X. 
@brawer @behdad : can you ping Apple about this?

**Comment by behdad** [comment] 2017-02-15 20:21
> @brawer @behdad : can you ping Apple about this?

Report it on bugreport.apple.com and send me their bug number.

**Comment by nizarsq** [comment] 2020-06-03 04:38
Currently not able to reproducible this issue.

**Comment by nizarsq** [comment] 2021-02-09 20:39
Issue not reproducible on Mac version 10.15.4 and Pages version 10.3.9 (7029.9.8). Closing the bug as WAI

<img width="1030" alt="Screen Shot 2021-02-09 at 12 36 16 PM" src="https://user-images.githubusercontent.com/22158882/107425189-82cc4180-6ad3-11eb-95c2-734e497e0952.png">

**Closed by nizarsq** 2021-02-09 20:39 UTC
Labels: Script-Arabic, app-dependent-behavior, in-evaluation
