### ISSUE TITLE
Wrong glyph for U+AB35 LATIN SMALL LETTER LENIS F

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1099] opened 2018-03-19 00:01 UTC
### Font
NotoSans-Regular.ttf
NotoSans-Italic.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Date: 2018-03-13

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+AB35 looks confusingly similar to U+0066. In the roman fonts, its leg should be truncated such that the letter hovers above the baseline. In the italic fonts, U+AB35 should have no tail. There is no need to truncate the leg above the baseline in the italic fonts.

### Character data
﻿﻿fꬵ
U+0066 LATIN SMALL LETTER F
U+AB35 LATIN SMALL LETTER LENIS F

### Screenshot
![﻿﻿fꬵ](https://user-images.githubusercontent.com/1124347/37572762-320404c0-2ae6-11e8-8f51-c52a3d070f39.png)![fꬵ](https://user-images.githubusercontent.com/1124347/37572751-175d74c6-2ae6-11e8-93fa-17898274bfc9.png)

**Comment by moyogo** [comment] 2018-03-19 06:25
Duplicate of #848

**Comment by nizarsq** [comment] 2020-07-14 00:29
This issue has been resolved for NotoSans-Regular and NotoSans-Italic.
<img width="565" alt="Screen Shot 2020-07-13 at 5 28 34 PM" src="https://user-images.githubusercontent.com/22158882/87366749-48df9080-c52e-11ea-9437-a3a1b17051a2.png">

**Closed by nizarsq** 2020-07-14 00:29 UTC
Labels: Script-LatinGreekCyrillic, wrong glyph(s)
