### ISSUE TITLE
Noto Sans: Vietnamese's ngã "tumbling" tone is just a horizontal line but not a `(low) falling and (mid) rising` or `creaking-rising`

### ISSUE THREAD

**Issue by samdx** [googlefonts/noto-fonts#750] opened 2016-09-28 16:51 UTC
Hi,

The following image shows the comparition between Noto Sans vs Lato Sans in displaying the Vietnamese's [ngã](https://en.wikipedia.org/wiki/Vietnamese_phonology#Six-tone_analysis) tone.

Here you can see, Noto Sans displays this tone just weird. It's a - (horizontal-line) instead of a ~.

The text in the left side was used Noto Sans font, and Lato is the right one, in comparision of displaying of the word `gõ` (the 2nd word from left in the example sentence).

My question, why it is and how to fix that?

Thanks.

![Noto Sans vs Lato Sans in Vietnamese's ngã tone](https://cloud.githubusercontent.com/assets/18287802/18922336/59baa11e-85d2-11e6-9d59-99892259b295.png)

(Really sorry for this so small font size!)

**Comment by marekjez86** [comment] 2016-09-28 23:55
@samdx : could you enter some sample text with all the tones for Vietnamese [sắc, huyền , hỏi , ngã  and nặng  ] over some vowels? I wanted to create a test for this and I'm not a Vietnamese speaker/reader/writer.

@waksmonskiMT : please consider changing it.

**Comment by samdx** [comment] 2016-09-29 05:17
@marekjez86 Here I added more some sample and comparision. Two font faces side by side, with various font sizes.

It seems that the issue is ocurred when using font sizes which are equal or smaller than 11pt only (`<=11pt`). (Red arrows)

![160929-fonts-comparison](https://cloud.githubusercontent.com/assets/18287802/18941824/7d53f168-863e-11e6-9e53-fd76e7b1a32c.png)

**Comment by moyogo** [comment] 2016-10-03 06:22
@lemzwerg This looks like an issue with freetype autohinting. The uppercase and lowercase tilde are flat at some sizes: 14 and 15 ppem for the uppercase, 10 to 15 and 18 to 20 ppem for the lowercase. They are not as flat with font hinting.

**Comment by lemzwerg** [comment] 2016-10-03 08:16
It most certainly is, if the font was either hinted with ttfautohint, or FreeType gets used in auto-hinting mode.  For the former it is possible to correct bad hinting manually, for the latter there is currently no fix.

**Comment by jungshik** [comment] 2016-10-11 17:54
I filed https://savannah.nongnu.org/bugs/index.php?49312 against FreeType.

**Comment by jungshik** [comment] 2016-10-11 17:56
@marekjez86,  what do you think of adding a new label for 'External Dependency'?

**Comment by jungshik** [comment] 2016-10-11 17:59
@KatMomoi ,  what's your take on tracking issues like this? This bug is not a bug in Noto fonts but an issue in FreeType. However, FreeType being widely used to render fonts, it affects how Noto looks (when FreeType autohinting mode is selected).

**Comment by marekjez86** [comment] 2016-10-21 20:26
@jungshik : added ExternalDependency label

**Comment by jungshik** [comment] 2016-11-01 22:48
If this only happens with FreeType autohinting in effect (i.e. it does not happen with BCI hint), we'd better close this bug. 

@marekjez86, can you check that out? You can download and build FreeType demo package and build one of ft* binaries that allow control hinting mode at run-time. 

My FreeType bug was duped to https://savannah.nongnu.org/bugs/?23537 (filed in 2008 but not yet fixed).

**Comment by lemzwerg** [comment] 2016-11-02 06:22
I've added more comments at https://savannah.nongnu.org/bugs/?23537

**Comment by TidharC** [comment] 2016-11-30 19:03
Fix verification in progress.

**Comment by marekjez86** [comment] 2017-01-04 15:41
MTI note: "Hints would help bring out the tilde shape at smaller sizes. Also to add a design made for small subhead sizes would solve the problem."

**Comment by lemzwerg** [comment] 2017-01-04 17:14
What does `small subhead sizes' mean?

**Comment by SteveMatteson** [comment] 2017-01-05 00:05
Subheadings are not text and not headlines… ‘small subhead’ would be an arbitrary size larger than text but not the largest headline size.  I would suggest something from 16 to 24pt in a document such as a newsletter is probably what the note refers to
Steve

On Jan 4, 2017, at 4:55 PM, lemzwerg <notifications@github.com<mailto:notifications@github.com>> wrote:


@TrueTyper<https://github.com/TrueTyper> , @SteveMatteson<https://github.com/SteveMatteson> : Could you explain "What does `small subhead sizes' mean?" in reference to the MTI note above?

**Comment by ariasuni** [comment] 2017-01-12 02:54
This problem happens with quite a few fonts for me, so the best solution right now seems to [change the `hintstyle` value](https://wiki.archlinux.org/index.php/Font_configuration#Hintstyle) (I have the problem with `hintslight` but not with the other values).

It doesn’t change the fact that the bug should be resolved either in the fonts or in fontconfig, but I though it might help some people by sharing this tip.

**Comment by jungshik** [comment] 2017-01-13 20:23
> MTI note: "Hints would help bring out the tilde shape at smaller sizes.

Did we have this problem with BCI hint applied?  I doubt so (I changed the title accordingly). **If** this issue manifests itself only with FreeType **autohint** ,  a change in the font (hint instruction change) wouldn't help. 

> to add a design made for small subhead sizes would solve the problem.

This could potentially help.

**Comment by ariasuni** [comment] 2017-01-13 21:05
On my machine, BCI is on. It’s on by default on Arch Linux, but I tried to set it on in my font configuration file to check, and indeed there’s the same problem.

**Comment by nizarsq** [comment] 2020-07-22 04:53
This issue seems to be fixed for NotoSans, NotiSerif and NotoSansMono
<img width="581" alt="Screen Shot 2020-07-21 at 9 52 01 PM" src="https://user-images.githubusercontent.com/22158882/88135628-6949c380-cb9c-11ea-8a7f-6f76d722f9ce.png">

**Closed by nizarsq** 2020-07-22 04:53 UTC
Labels: ExternalDependency, Script-LatinGreekCyrillic, Status-ReadyForVerification, in-evaluation
