### ISSUE TITLE
Invisible Nastaliq letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2240] opened 2022-02-05 15:26 UTC
### Font
NotoNastaliqUrdu-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/f7556efcaf940cf6c2f8ae0c3386d651e930b5cc/unhinted/otf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.otf
Date: 2022-02-03

### Font version
Version 3.002

### Issue
Some positional forms of some letters have partly or wholly invisible glyphs.

### Character data
<span dir="auto">[ؠ]</span>
U+005B LEFT SQUARE BRACKET
U+0620 ARABIC LETTER KASHMIRI YEH
U+005D RIGHT SQUARE BRACKET
<span dir="auto">[ݺل لݺل]</span>
U+005B LEFT SQUARE BRACKET
U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+0644 ARABIC LETTER LAM
U+0020 SPACE
U+0644 ARABIC LETTER LAM
U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+0644 ARABIC LETTER LAM
U+005D RIGHT SQUARE BRACKET
<span dir="auto">[ݻل لݻل]</span>
U+005B LEFT SQUARE BRACKET
U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+0644 ARABIC LETTER LAM
U+0020 SPACE
U+0644 ARABIC LETTER LAM
U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+0644 ARABIC LETTER LAM
U+005D RIGHT SQUARE BRACKET
<span dir="auto">[ࢬ]</span>
U+005B LEFT SQUARE BRACKET
U+08AC ARABIC LETTER ROHINGYA YEH
U+005D RIGHT SQUARE BRACKET

### Screenshot
![[ؠ] [ݺل لݺل] [ݻل لݻل] [ࢬ]](https://user-images.githubusercontent.com/1124347/152647812-8b58d5a5-466c-4bf2-b2ae-8e16926b3010.png)

**Comment by simoncozens** [comment] 2022-02-06 07:51
Thanks. There are some decompositions missing. I will get onto them.

**Comment by simoncozens** [comment] 2022-02-08 11:55
OK, I can fix most of these, but something is happening with the modified bari ye that I don't understand. The problem is that  when shaping `077A 0644` the bari ye is being marked as being in initial position; because there's no `init` rule for bariye (because there is no such thing as initial bari ye!) you get the placeholder glyph. You can see that the shaping is broken because the lam is being placed in the final form even though bari ye is right-joining. This feels like a problem either with Harfbuzz or with Unicode!

**Comment by simoncozens** [comment] 2022-02-08 11:59
@r12a Any ideas why U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE and U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE are specified as being dual-joining? Is this an oversight or do those glyphs do something clever I'm not expecting?

```
06D2; YEH BARREE; R; YEH BARREE
06D3; YEH BARREE WITH HAMZA ABOVE; R; YEH BARREE
...
077A; BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE; D; BURUSHASKI YEH BARREE
077B; BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE; D; BURUSHASKI YEH BARREE
```

**Comment by simoncozens** [comment] 2022-02-08 12:13
Ah, I went and read the encoding proposal, and yes, these characters *do* do something clever I'm not expecting.

**Comment by khaledhosny** [comment] 2022-02-08 13:19
They have a different joining group for this reason.

**Comment by simoncozens** [comment] 2022-02-08 13:27
Yes, found it; they behave like choti ye in init/medi.

**Closed** 2022-03-01 14:56 UTC
Labels: Script-Nastaliq
