### ISSUE TITLE
Knots are missing in Bengali font

### ISSUE THREAD

**Issue by Sagir8453** [googlefonts/noto-fonts#1007] opened 2017-12-01 08:37 UTC
## Defect Report
Hi, traditionally and also in current handwritten and serif fonts many Bengali characters have knots which are essential in Bengali/Assamese script. But many sans fonts 
including Noto Sans Bengali don't have knots in Bengali fonts while they have knots in other scripts (example: Devanagari ढ, Gujarati જ, Tamil அ etc), except for one Bengali character: ঙ. Knots should be added to Bengali font too. 
The characters that need knots are অ আ ই ঈ এ ঐ ও ঔ ক খ ঞ ট ঢ ণ ত থ ধ ন ফ ভ ম ল শ হ ঢ় ১ ৩ and ৯ .
### Font 
  > NotoSansBengali-Regular.ttf.

### Source of the font
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBengali-hinted.zip
  >   Date: 2017-01-12

**Comment by Sagir8453** [comment] 2017-12-14 15:36
Hi, I don't know how to add image. But you can look at the handwriting of Rabindranath Tagore here https://goo.gl/images/oFEXzi 
He uses knots. Also you can check other handwritings and manuscripts of Assamese and Bengali. Knots are important, please don't promote the wrong way of writing. As a teacher of the script I have to tell learners that the font isn't correct, you should write like that. Please take a look at this issue.

**Comment by Sagir8453** [comment] 2017-12-26 17:02
Atleast add knots in ম and শ (like in Noto Serif Bengali) . ম looks like স but ম is very different in the script. It should create a knot like ૪. It's like writing 6 like C.

**Comment by Sagir8453** [comment] 2019-01-12 15:51
Hi, no it's not regional. Maybe some made an experimental Sans font without
knots for some reasons and it was followed by some other sans fonts. In all
regions where this script is used we learn that adding knots/blobs is
important. It's always added in good handwritings. You can see in the
images written in Bengali language has knots. It's wrong if we don't add
knots. If you google "Bengali handwriting" or "Assamese handwriting", texts
with knots will appear. Tatsam Bengali sans font has knots.

**Comment by Sagir8453** [comment] 2019-01-12 19:46
Is Noto Sans Bengali based on/inspired by Syam Rupali font? I think Syam
Rupali isn't a nice looking font. Its characters are experimental and
doesn't follow traditional rules. It's fine in its own place but Noto fonts
which are used in Android devices should not be based on any experimental
font (or should not be experimental). They should preserve the traditional
way rather that creating a new way. For many scripts I think Noto fonts are
best in doing that. But for Bengali and now Tirhuta, some misconceptions
happened.

**Comment by Sagir8453** [comment] 2019-01-12 19:48
Ops, I meant "Rupali font"* not "Siyam rupali font".

**Comment by Sagir8453** [comment] 2019-01-13 11:20
![bg-25-6-e1432886609382](https://user-images.githubusercontent.com/22221772/51084628-214e1300-1753-11e9-893e-fafa4a732024.jpg)
Bengali text with knots 
![images 18](https://user-images.githubusercontent.com/22221772/51084629-35921000-1753-11e9-8770-9a50a367fd2e.jpeg)
Tatsam Bengali sans font has knots

**Comment by Sagir8453** [comment] 2019-01-13 11:21
![cb90cb4c893afed0c6d0d640435aeac0](https://user-images.githubusercontent.com/22221772/51084641-5a868300-1753-11e9-955c-c4b5081d6524.jpg)
Bengali texts with knots.
![images 18](https://user-images.githubusercontent.com/22221772/51084646-696d3580-1753-11e9-98f6-764962d65b84.jpeg)
Tatsam Bengali (sans) font has knots.

**Comment by Sagir8453** [comment] 2019-01-14 11:48
![fb_img_1547466195580](https://user-images.githubusercontent.com/22221772/51110886-29c04f80-1820-11e9-8a09-530b58e22fff.jpg)
@marekjez86 A Sans font with knots, from Bangladesh (ignore what's written).

**Comment by marekjez86** [comment] 2019-03-21 18:31
same issue https://github.com/googlei18n/noto-fonts/issues/1422

**Comment by marekjez86** [comment] 2020-06-15 21:47
duplicate of https://github.com/googlefonts/noto-fonts/issues/1422

**Closed by marekjez86** 2020-06-15 21:47 UTC
Labels: Script-Bengali, Type-Enhancement, in-evaluation, non-Traditional
