### ISSUE TITLE
NotoSans-Regular mis-places cedilla in Ó̧

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#635] opened 2016-03-08 18:32 UTC
In NotoSans-Regular, the string Ó̧ (U+00D3 U+0327) has the cedilla misplaced. Admittedly this is an exotic sequence, but it still seems surprising that it doesn't work. Other fonts such as Gentium-Regular can render the same sequence without displacing the cedilla.

``` bash
$ wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
$ unzip NotoSans-unhinted.zip
$ hb-view NotoSans-Regular.ttf --output-format=png Ó̧ >O.png
$ hb-view --version
hb-view (HarfBuzz) 1.2.1
```

Noto Sans Regular:
![o](https://cloud.githubusercontent.com/assets/1527880/13611553/745e25e6-e563-11e5-8ce0-9864cb09704e.png)

Gentium Regular:
![o-gentium](https://cloud.githubusercontent.com/assets/1527880/13611736/47c9f0ea-e564-11e5-95df-49306f648af4.png)

**Comment by brawer** [comment] 2016-03-08 18:38
See https://fr.wikipedia.org/wiki/%C3%93%CC%A7 for a web page that uses this grapheme.

**Comment by roozbehp** [comment] 2016-03-08 22:41
@brawer, does this happen for Noto Serif too?

**Comment by brawer** [comment] 2016-03-09 08:20
Yes.

**Comment by marekjez86** [comment] 2016-03-09 17:26
I did an experiment with the newest OTF fonts build by the Glyphs app from glyphs files delivered within the last few months. Note that I have an old version of hb-view (hb-view --version yields: 
"hb-view (HarfBuzz) 0.9.41
Available shapers: ot,fallback")

hb-view NotoSansUI-Regular.otf --output-format=png Ó̧ >OsansUI.png
yields
![osansui](https://cloud.githubusercontent.com/assets/13322623/13644049/a3231b5a-e5d8-11e5-937f-b918abaed93d.png)


hb-view NotoSansMonoUI-Regular.otf --output-format=png Ó̧ >OsansMonoUI.png
yields
![osansmonoui](https://cloud.githubusercontent.com/assets/13322623/13644005/7ef90c08-e5d8-11e5-9c34-22d2f112ba30.png)

hb-view NotoSerif-Regular.otf --output-format=png Ó̧ >Oserif.png
yields
![oserif](https://cloud.githubusercontent.com/assets/13322623/13644037/9b281612-e5d8-11e5-8be9-e18ccc786afe.png)

Do not have Noto Sans font to check.
I'll download the fonts that Sascha used and see the results. I'll also check the pipeline generated fonts (as opposed to glyphs).

**Comment by marekjez86** [comment] 2016-03-09 17:35
I can repeat the same result (as @brawer ) using my old version of hb-view. I'll check the newest OTF fonts build by the pipeline from glyphs files delivered within the last few months.

**Comment by marekjez86** [comment] 2016-03-09 17:49
Using pipeline build OTF files:

hb-view NotoSerif-Regular.otf --output-format=png Ó̧ >Oserif.png
![oserif](https://cloud.githubusercontent.com/assets/13322623/13644558/3b749e72-e5db-11e5-90db-eda881f7942a.png)

hb-view NotoSansUI-Regular.otf --output-format=png Ó̧ >OsansUI.png
![osansui](https://cloud.githubusercontent.com/assets/13322623/13644583/62c0ca1e-e5db-11e5-9b62-8d6a693df5f3.png)

hb-view NotoSansMonoUI-Regular.otf --output-format=png Ó̧ >OsansMonoUI.png
![osansmonoui](https://cloud.githubusercontent.com/assets/13322623/13644599/7615ca2e-e5db-11e5-9540-7ead415fd708.png)

I'm confused by the difference between Oserif.png generated from the Glyphs app OTF (good) and one generated by the pipeline OTF. I attached both OTF files if anybody wants to test.

[NotoSerif-Regular.zip](https://github.com/googlei18n/noto-fonts/files/165732/NotoSerif-Regular.zip)

**Comment by marekjez86** [comment] 2016-03-09 18:16
Pipeline created italic OTF created from glyphs file

hb-view NotoSerif-Italic.otf --output-format=png Ó̧ >OserifItalic.png

![oserifitalic](https://cloud.githubusercontent.com/assets/13322623/13645437/debfd304-e5df-11e5-97a3-559daff7f711.png)

**Comment by marekjez86** [comment] 2016-03-09 18:17
I'll check again Serif. If I confused the output and it looks good then the problem is fixed in the newest deliveries.

**Comment by moyogo** [comment] 2016-03-09 18:33
This also happens with some Kiowa letters with diacritics above and below: Ḗ̱ ḗ̱ Ḕ̱ ḕ̱ Ṓ̱ ṓ̱ Ṑ̱ ṑ̱
Other similar Kiowa letters seem to be alright: Ā̱́ ā̱́ Ā̱̀ ā̱̀ Ā̱̂ ā̱̂ Ē̱̂ ē̱̂ Ī̱́ ī̱́ Ī̱̀ ī̱̀ Ī̱̂ ī̱̂ Ō̱̂ ō̱̂ Ū̱́ ū̱́ Ū̱̀ ū̱̀ Ū̱̂ ū̱̂.

**Comment by marekjez86** [comment] 2016-03-09 21:09
@moyogo I believe the following is correct:

hb-view NotoSerif-Italic.otf --output-format=png 'Ḗ̱ ḗ̱ Ḕ̱ ḕ̱ Ṓ̱ ṓ̱ Ṑ̱ ṑ̱' >kiowa.png

![kiowa](https://cloud.githubusercontent.com/assets/13322623/13650558/1b955b2e-e5f8-11e5-8430-6622d49a447a.png)

Please advise.

**Comment by moyogo** [comment] 2016-03-10 10:19
@marekjez86 I'm looking at the released fonts.

Le mer. 9 mars 2016 21:09, Marek Jeziorek <notifications@github.com> a
écrit :

**Comment by marekjez86** [comment] 2016-03-10 14:19
I'm aware you are looking at the released fonts and we have a bug there. I
just wanted to check the fonts that are "in progress" and see if this is
fixed there. I do not know the correct look hence I wanted your opinion if
the image that I posted is what you'd expect.

**Closed** 2021-02-12 04:34 UTC
Labels: Script-LatinGreekCyrillic

**Comment by nizarsq** [comment] 2021-02-12 04:50
@marekjez86  Ó̧ (U+00D3 U+0327) look good to me.
hb-view:
![O](https://user-images.githubusercontent.com/22158882/107731265-60d8e780-6caa-11eb-833c-2f5a1f3d3656.png)

Chrome:
<img width="749" alt="Screen Shot 2021-02-11 at 8 48 54 PM" src="https://user-images.githubusercontent.com/22158882/107731363-abf2fa80-6caa-11eb-9ddb-2a36a113571c.png">
