### ISSUE TITLE
COMBINING GRAVE ACCENT in Noto Sans

### ISSUE THREAD

**Issue by benk-cogapp** [googlefonts/noto-fonts#729] opened 2016-08-02 08:36 UTC
The COMBINING GRAVE ACCENT is required for ALA-LC transliteration of Hebrew and Yiddish - see page 6 of http://www.loc.gov/cds/desktop/documents/Hebraica_cataloging.pdf and an example record at http://www.yiddishbookcenter.org/collections/yiddish-books/spb-nybc200956.

We generally do well with Noto Serif using precombined characters, but as there isn't a precombined character LATIN SMALL LETTER S WITH GRAVE this falls back to the system font. As far as I can see this isn't available in the standard font or any of the supplementary fonts, and would be useful addition.

**Comment by moyogo** [comment] 2016-08-02 09:38
@benk-cogapp It sounds like you’re getting a subsetted font from somewhere since COMBINING GRAVE ACCENT is in Noto Serif and Noto Sans.

**Comment by benk-cogapp** [comment] 2016-08-02 09:47
@moyogo If you could point me in the direction of a web version that supports this that would be great. We're currently using the embedded version from Google Fonts which, from the CSS file, doesn't cover the required code points for COMBINING GRAVE ACCENT. I've also tried downloading Noto Serif from the Noto website and converting it to a web-font with no success.

**Comment by moyogo** [comment] 2016-08-02 09:55
@davelab6 can help you with that. See https://developers.google.com/fonts/docs/getting_started#specifying_script_subsets

**Comment by benk-cogapp** [comment] 2016-08-02 12:04
@moyogo @davelab6 Thanks, that's helpful - I see from playing with the the beta feature that I can make this work by requesting the font like this:

```
<link href="https://fonts.googleapis.com/css?family=Noto+Serif&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Noto+Serif&amp;text=doyres̀" rel="stylesheet" />
```

However, it doesn't work correctly without explicitly requesting the COMBINING GRAVE ACCENT, and I can see from the `unicode-range` in the standard stylesheet that this character (U+0300) isn't included in the requested subsets. It would be nice to have a standard subset that included these modifier characters.

**Comment by jungshik** [comment] 2016-08-03 23:16
Google Web Font is not very good when it comes to combining character support for Latin-Greek-Cyrillic given that it split a font into multiple subsets. To which subset would you put combining diacritic marks? I'll raise an issue internally to offer a way to get the *full* font.

**Comment by benk-cogapp** [comment] 2016-08-04 08:25
@jungshik Thanks for the follow-up. Looking at the existing subsets I'm not sure any of them would be appropriate - they all seem to fit within existing Unicode blocks, which makes sense, and in an ideal world it would be nice (for us) to get the whole Combining Diacritical Marks block. If pushed I'd say `latin-ext` since it already contains general punctuation and currency symbols, but I'm aware we're probably operating outside of most common use cases.

In an ideal world being able to retrieve the full font in a more nuanced way than 'everything', but a more practical way than 'specify each individual character up front' would be nice. The `unicode-range` CSS property isn't well supported enough for this, but being able to specify unicode ranges or blocks in the request would be great, so rather than putting in all the literal characters being able to form a request like:

```
<link href="https://fonts.googleapis.com/css?family=Noto+Serif&unicode-range=U+0300-U+036F" rel="stylesheet" />
```

Possibly as an alternative method of calling the beta font optimisation.

**Comment by jungshik** [comment] 2016-08-04 19:22
@benk-cogapp : Note that having a *separate* font-face (subset) with unicode-range set to 'Combining Diacritic Mark block' does NOT work because 'base' characters and combining marks will be in *multiple*  fonts (TTF or OTF) and GSUB/GPOS features cannot be applied across multiple fonts. 
For instance, the following does not work. 

```
@font-face { font-family: Noto Serif; 
                          src: url(..../noto_serif_latin.woff2) ...
                          unicode-range: for Latin 
                        }
@font-face { font-family: Noto Serif; 
                          src: url(..../noto_serif_latin_ext.woff2) ...
                          unicode-range: for Latin Ext
                        }

@font-face { font-family: Noto Serif;
                           src: url (..... combiningmark.woff2);
                           unicode-range: U+0300 - 03FF;
                         }
```


I have yet to check the spec and implementations of 'unicode-range' as to what they specify and do when overlapping unicode-ranges are specified for font-face. If the first font-face entry or the last claiming to cover a code point trumps all other font-faces entry claiming to cover the code point, there might be a way to deal with this.

**Comment by jungshik** [comment] 2016-10-12 22:37
@benk-cogapp , can you serve your own web fonts?  Then, you can just use the full Noto Serif or Noto Sans.  

An alternative is (I confirmed that it kinda works) to do the following:

```
<style>
@font-face { 
   font-family: Noto Serif;
   .....
   src: url(NotoSerif-Regular.ttf);   /* this is the full Noto Sserif  served from your server */ 
}
</style>

<link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
```

With that, the full Noto Serif will be downloaded only when you need to use 'base + combining marks' (because Chrome determins which font to use based on graphme-cluster coverage rather than 'code point' coverage). Otherwise, smaller subsets will be downloaded from Google Font. 

I confirmed that it works with Chrome, but Firefox does not (needs more investigation).

**Comment by nizarsq** [comment] 2020-07-22 05:55
@benk-cogapp Look like U+0300( ̀) is exist in NotoSans NotoSansMono and NotoSerif. Fonts used in my test can be found here:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif
Going to close this bug for now, if you have other thoughts please reopen
<img width="546" alt="Screen Shot 2020-07-21 at 10 50 43 PM" src="https://user-images.githubusercontent.com/22158882/88139465-9dc17d80-cba4-11ea-9ff3-e8e016ecfa95.png">

**Closed by nizarsq** 2020-07-22 05:55 UTC
Labels: Script-LatinGreekCyrillic, in-evaluation
