### ISSUE TITLE
Noto Myanmar needs to support dotted forms

### ISSUE THREAD

**Issue by roozbehp** [googlefonts/noto-fonts#563] opened 2015-11-12 01:51 UTC
Unicode accepted variation sequences for dotted style of some Myanmar letters for Unicode 9. The proposal is at http://www.unicode.org/L2/L2015/15320-khamti-vs.pdf. (Note that the shape of U+AA7A at the end of the table in page 3 is incorrect: it should have a dot, similar to U+101C.)

This needs to be supported in two ways:
1. The new variation sequences need to be supported, irrespective of the language. If a variation sequence is there, the dotted form of that letter should be used for that letter only.
2. 'locl' features should be added for Khamti, Aiton, and Phake, which map the normal glyphs to the dotted glyphs.

/cc @kmansourMT @mhosken @sven-oly

**Comment by andjc** [comment] 2016-01-04 07:04
The proposal only gives the Khamti Shan normative glyphs, it does not show the Tai Aiton and Tai Phake glyphs which differ from the Khamti Shan glyphs in many cases. A useful source of information is the original Unicode proposal for Khamti, Aiton and Phake. This detail isn't captured in either the disunifcation proposal, the Unicode standard or UTN11.

Additionally none of the sources discuss Aiton and Phake reduplication vis-a-vis Khmati reduplication.

**Comment by jungshik** [comment] 2016-10-12 17:51
@KatMomoi, could you verify that this issue was addressed in the latest delivery?

**Comment by TidharC** [comment] 2016-11-02 22:58
Looks like the dotted forms are not available as of Noto Sans Myanmar 1.10

**Comment by marekjez86** [comment] 2016-11-05 00:24
@TidharC : could you check with the following fonts to be tested with; it's OK to pick just Regular and Bold of each kind [NotoMyanmar.zip](https://github.com/googlei18n/noto-fonts/files/572893/NotoMyanmar.zip)

**Comment by marekjez86** [comment] 2016-11-09 17:12
[NotoSansMyanmar3-Bold-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581416/NotoSansMyanmar3-Bold-MN.pdf)
[NotoSansMyanmar3-Regular-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581415/NotoSansMyanmar3-Regular-MN.pdf)


[fontdiff](https://github.com/googlei18n/fontdiff) test file is in the following zip

[Myanmar3.html.zip](https://github.com/googlei18n/noto-fonts/files/581419/Myanmar3.html.zip)

**Comment by dougfelt** [comment] 2017-03-29 19:00
This fontdiff test file doesn't include FE00 sequences, and the font doesn't include a format 14 cmap.  We should confirm that the variation selector sequences mentioned by Roozbeh do, in fact, work.  @marekjez86 can you follow up?

**Comment by Kanjilearner817** [comment] 2017-03-29 20:30
It would appear that I had the right idea in having Phase III Myanmar CMAPs updated ahead of this, then.

**Comment by dougfelt** [comment] 2017-03-29 20:44
It was the right idea.  I could have been clearer-- it appears the Myanmar cmaps do in fact already include FE00, and they may in fact support variation sequences as described in the Unicode proposal via GSUB.  I have not investigated the GSUB tables to see via inspection whether they do, but I'm hoping, since the character is present in the font, that this is the case.  At any rate we should have a test.

**Comment by kmansourMT** [comment] 2017-03-29 21:28
In Noto Myanmar, the dotted variants are selected through the GSUB.

**Comment by andjc** [comment] 2017-03-30 02:58
Is there any particular reason that the fonts only support Khmati style glyphs and not Tai Aiton or Tai Phake style glyphs?

**Comment by kmansourMT** [comment] 2017-03-30 17:53
Noto Myanmar fonts support all the Standardized Variants as specified by the Unicode Standard v. 9.

**Comment by andjc** [comment] 2017-03-31 13:17
@kmansourMT, the variation selector was intended to distinguish between dotted and non-dotted forms, and that was considered sufficient, ie it wasn't necessary to introduce two additional variation selectors, to cater for all variations. 

But that doesn't necessarily mean that all variations are excluded. Rather I suspect it means that the glyphs displayed by the variation selectors are depended on which opentype language system is being used. 

Also note the behaviour of U+AA7A U+FE00
U+AA7A by itself is the undotted form
U+AA7A U+FE00 when it is Khamti Shan is also the undotted form (and since you are using Khamti Shan as the normative form for theses glyphs U+AA7A and UAA7A U+FE00 would be identical undotted glyphs). 
U+AA7A U+FE00 when it is Aiton is the dotted form.

**Comment by marekjez86** [comment] 2017-09-20 00:57
see [almost] duplicate #780
see [almost] duplicate #930

**Comment by ohbendy** [comment] 2018-05-09 23:37
> Noto Myanmar fonts support all the Standardized Variants as specified by the Unicode Standard v. 9.

The problem is the Unicode charts encode characters, not the glyphs needed by different orthographies. For example, as Andrew mentions, Aiton and Phake are visually very different from Khamti, yet some of the letters share codepoints. This goes for many of the eighteen orthographies that I researched and drew in the source files I submitted. It's a shame these have been removed, since now we have fonts that support the Unicode charts but do not support the languages properly (i.e. following the conventional orthographic representations of different communities). As well as the source files, I submitted documentation of which glyphs to use for which minority languages, there was a whole bunch of work that has just been dropped at the engineering stage. My intention was to treat the minority languages just as deliberately as Standard Burmese (why should they be less important), so I'm very sorry to see that the Noto fonts (which state the aim of supporting all languages, not Unicode charts) still do not allow comfortable digital communication for those user groups.

**Comment by nizarsq** [comment] 2020-08-12 04:59
Dotted forms looks good in NotoSansMyanmar and NotoSerifMyanmar (Regular and Bold) this include U+AA7A (ꩺ).
<img width="1431" alt="Screen Shot 2020-08-11 at 9 52 23 PM" src="https://user-images.githubusercontent.com/22158882/89976308-f2449f80-dc1c-11ea-821b-ad6689b10323.png">
<img width="1430" alt="Screen Shot 2020-08-11 at 9 52 53 PM" src="https://user-images.githubusercontent.com/22158882/89976339-04264280-dc1d-11ea-8771-f902eac17b8e.png">
<img width="1433" alt="Screen Shot 2020-08-11 at 9 53 16 PM" src="https://user-images.githubusercontent.com/22158882/89976358-11dbc800-dc1d-11ea-8ae5-cb77448adfa3.png">

**Closed by nizarsq** 2020-08-12 04:59 UTC
Labels: Android, Priority-Medium, Script-Myanmar, Type-Enhancement, help wanted

**Comment by ohbendy** [comment] 2020-08-12 07:06
Right, if you're only concerned about getting dotted forms. If you're thinking about supporting the different languages, as mentioned above, Aiton, Phake and Khamti prefer different glyphs. I'm reviewing the Noto Myanmar fonts anyway, so I'll make sure full info about this is included.

**Comment by nizarsq** [comment] 2020-08-12 18:03
> Right, if you're only concerned about getting dotted forms on the consonants: vowels and other symbols should also be dotted.
> 
> If you're thinking about supporting the different languages, as mentioned above, Aiton, Phake and Khamti prefer different glyphs. I'm reviewing the Noto Myanmar fonts anyway, so I'll make sure full info about this is included.

@ohbendy , I need to go over the bug again and reopen if needed.  Thank you

**Comment by nizarsq** [comment] 2020-08-12 19:41
@marekjez86 what is the status of 'locl' feature in Myanmar?
