### ISSUE TITLE
Noto Sans & Serif 2.0 & others: MS Code Pages not selected

### ISSUE THREAD

**Issue by librarhyme** [googlefonts/noto-fonts#1005] opened 2017-11-30 13:35 UTC
## Noto Sans & Serif 2.0 & others: MS Code Pages not selected
Thus not recognised by, and not properly showing in, Word 2016. 

### Issue
![171130](https://user-images.githubusercontent.com/28468666/33433064-27b6232a-d615-11e7-8257-00530cedbaf8.PNG)

### Font 
  > NotoSans-Regular.ttf
  > NotoSans-Italic.ttf
  > NotoSans-Condensed.ttf
  > NotoSans-Medium.ttf
  > NotoSerif-Regular.ttf
**etc. and many many others.**

### Where the font came from, and when
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip
  >   Date: 2017-11-29

### Font Version
  > 2.00

### OS name and version
  > Windows 8 Pro

### Application name and version
  > Office Word 2016, Version 1609 (Build 7369.2127)

**Comment by codeman38** [comment] 2017-11-30 22:52
Duplicate of #902. This should probably be fixed up manually, if nothing else, now that the alpha fonts have been promoted to the main repo.

**Comment by anthrotype** [comment] 2017-12-01 11:03
The toolchain already supports compiling the codepage bits if they are specified in the glyphs or ufo source using the respective fields. For Noto sources which uses Glyphs.app, the `codePageRanges` custom parameter should be set accordingly. UFO has the equivalent openTypeOS2CodePageRanges in fontinfo.plist

**Comment by nizarsq** [comment] 2020-07-18 05:12
@librarhyme could you check if this issue still reproducible in the latest build in these directories:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif

**Comment by moyogo** [comment] 2021-03-10 07:44
Duplicate of #902.

The code page ranges were fixed in Noto Sans 2.001 (4b9da60ee), Noto Sans Mono 2.002 (4b9da60ee), Noto Serif 2.001 (449470a4d) when the fonts were build with fontmake after googlefonts/fontmake#304 was merged.

**Closed by moyogo** 2021-03-10 07:44 UTC
Labels: Script-LatinGreekCyrillic, app-dependent-behavior, in-evaluation
