### ISSUE TITLE
Major flaw with Batak Noto font

### ISSUE THREAD

**Issue by ulikozok** [googlefonts/noto-fonts#1844] opened 2020-09-08 12:01 UTC
### Title 
Major flaw 
### Font 
Noto Sans Batak-Regular
### Issue
I am Dr. Uli Kozok, specialist on Batak philology and palaeography at the University of Hawaii.  I developed the first Batak font, and then with Michael Everson the first unicode font. Michael's Pangururan font has it's own flaws, but Noto has one major flaw - besides a whole range of minor flaws that I will address later - which is the most profound flaw. Daan van Esch suggested that I should post it here. Thank you! 

If I want to write the Batak name Simbolon, the Batak Noto font allows me to write the sequence sim\bolon\ where \ represents the virama. However, this is not how the Batak script works. In the Batak script the vowel in a closed syllable (where the vowel is not a) must be written following the two consonants and before the virama. Why is this so? Nobody knows. None of the Indonesian scripts has this odd rule, but, well, it is how it is. Therefore the sequence sim\bolon\ (for Simbolon) is wrong. The correct way to write it, is smi\bolno\. The latter correct form is "penalized" by displaying a little dotted circle marking it "wrong". (see screenshot *sorry, don't know how to* )

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by dscorbett** [comment] 2020-09-08 13:03
This was already reported in #624.

<i>The Unicode Standard</i> says [in chapter 17](https://www.unicode.org/versions/Unicode13.0.0/ch17.pdf#page=19):

> The main peculiarity of Batak rendering concerns the reordering of the glyphs for vowel signs when one of the two killers, <i>pangolat</i> or <i>panongonan</i>, is used to close the syllable by killing the inherent vowel of a final consonant. This reordering for display is entirely regular. So, while the representation of the syllable /tip/ is done in logical order: <<i>ta</i>, <i>vowel sign i</i>, <i>pa</i>, <i>pangolat</i>>, when rendered for display the glyph for the vowel sign is visually applied to the final consonant, <i>pa</i>, rather than to the <i>ta</i>. The glyph for the <i>pangolat</i> always stays at the end of the syllable.

Your example of <U+1BD8 BATAK LETTER SA, U+1BD4 BATAK LETTER MA, U+1BEA BATAK VOWEL SIGN I, U+1BF2 BATAK PANGOLAT> gets a dotted circle because the order does not match the order specified in the standard. The correct order is <U+1BD8 BATAK LETTER SA, U+1BEA BATAK VOWEL SIGN I, U+1BD4 BATAK LETTER MA, U+1BF2 BATAK PANGOLAT>. It is up to the font to reorder the vowel sign. Unfortunately, Noto Sans Batak does not reorder the vowel sign and is thus unusable.

**Comment by ulikozok** [comment] 2021-07-17 23:41
<U+1BD8 BATAK LETTER SA, U+1BD4 BATAK LETTER MA, U+1BEA BATAK VOWEL SIGN I, U+1BF2 BATAK PANGOLAT> is CORRECT.  So what shall be done now? The font needs to be corrected as it is unusable. Please look at https://aksara-batak.com/blog/2021/07/16/noto-batak-sans-font/?lang=en

**Comment by dscorbett** [comment] 2021-07-18 02:30
It sounds like you disapprove not just of this font but also of Unicode’s Batak encoding model. Have you submitted a proposal to Unicode requesting they change the encoding model? The dotted circle is being inserted by the shaper, not by the font, so if the encoding model changes, the current version of the font will start working once the shaper is updated. If the encoding model does not change, Google should (in my opinion) hire someone to fix the reordering. The fix is obvious and easy to implement.

**Comment by punchcutter** [comment] 2021-07-24 13:18
<img width="273" alt="batak1844" src="https://user-images.githubusercontent.com/11257204/126869629-2ca71134-12b7-45d6-ae44-2cb6f506feeb.png">
Updated font reorders according to Unicode. Here is old (top), new (bottom) showing ᯤᯉᯬᯉ᯲

**Comment by marekjez86** [comment] 2021-07-25 19:05
@ulikozok : please check https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansBatak or https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansBatak

**Comment by simoncozens** [comment] 2022-04-23 07:10
Closing as a duplicate of #624.

**Closed by simoncozens** 2022-04-23 07:10 UTC
Labels: Script-Batak
