### ISSUE TITLE
Noto Arabic Naskh should have language specific variants

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#773] opened 2016-10-16 17:00 UTC
SIL have made a list of language specific form for mark positioning and character variants:
![SIL’s example](http://software.sil.org/scheherazade/wp-content/uploads/sites/29/2016/03/Scheherazade-LanguageFeaturesNew.png)

Additionaly I found the letter ۇ has a variant in Uyghur, its diacritic should be comma shaped, not 9 shaped, if you go to Xinjiang, PR China, you will see it everywhere.

**Comment by KrasnayaPloshchad** [comment] 2016-10-16 17:10
Uyghur Computer Science Association (http://www.ukij.org) also provided a code chart with Uyghur specific forms.
![2004-1-17_Birlikke_Kelgen_Uyghurche_Herpler_Kod_Jedwili.gif](http://www.ukij.org/fonts/image/2004-1-17_Birlikke_Kelgen_Uyghurche_Herpler_Kod_Jedwili.gif)

**Comment by nizarsq** [comment] 2016-10-17 16:44
Which OS and App are you using? tested on textedit on TextEdit on Mac OS 10.11.6 and was not able to reproduce the issue.

**Comment by jungshik** [comment] 2016-10-17 20:36
> Which OS and App are you using? tested on textedit on TextEdit on Mac OS 10.11.6 and was not able
> to reproduce the issue.

@nizarsq How did you test what's requested in this bug with TextEdit?  

You should make an HTML document and put test strings in a span tagged by different languages mentioned in the bug report to see if they're differently shaped. 

An alternative is to use hb-shape and pass the test string and 'lang' and see if they're shaped in a language-dependent manner.

**Comment by nizarsq** [comment] 2016-10-17 22:42
@jungshik Thanks for your comment, my previous comment has typo error, I repeated textedit twice, I apologize. I tried to test some scenarios reporter mentioned in the bug using TextEdit as editor on Mac OS 10.11.6 but I got some different results, since the initial bug didn't mention details like OS or App etc..  I asked for more details to be able to reproduce the issue/issues so I verify the behavior before triage the bug. Thanks

![screen shot 2016-10-17 at 3 32 11 pm](https://cloud.githubusercontent.com/assets/22158882/19458109/e46adfa8-947e-11e6-8d63-bda93611efff.png)

**Comment by KrasnayaPloshchad** [comment] 2016-10-18 08:23
@nizarsq Oh I forgot to test them. Now I downloaded & installed Noto Arabic Naskh and I make tests for them on Firefox 49.0 on Windows 10.

Test 1: test all these characters that could have these variants.
![1](https://cloud.githubusercontent.com/assets/10364351/19469727/1d0e1278-954f-11e6-9eae-19a40cbb91ef.PNG)
Test 2: test with all Kurdish individual codes.
![2](https://cloud.githubusercontent.com/assets/10364351/19469742/2b4b4400-954f-11e6-9c9a-f707cc96b877.PNG)

**Comment by nizarsq** [comment] 2016-10-18 15:19
@KrasnayaPloshchad thank you for updates thats much better, I will go over the bug again. Thanks

**Comment by jungshik** [comment] 2016-10-18 17:26
> I tried to test some scenarios reporter mentioned in the bug using TextEdit as editor o

My point is that you cannot specify 'lang' in TextEdit. You cannot test what's reported in this issue (language-dependent shaping behavior / glyph forms)  with TextEdit. 

You have to do either of the two methods I described in my earlier comments. Actually, doing both would be the best. 

1) Use HarfBuzz - tip of the tree version
2) Use HarfBuzz - the latest release version
3) Use Chrome (dev channel)

**Comment by nizarsq** [comment] 2016-10-21 16:25
@KrasnayaPloshchad Do you have an example of a font that have language specific variants?

**Comment by KrasnayaPloshchad** [comment] 2016-10-22 02:49
@nizarsq OK, recently I found an official website of Xinjiang showing localized ۇ which diffrerent from Moddle East
http://uygur.xinjiang.gov.cn/

**Comment by KrasnayaPloshchad** [comment] 2016-10-24 04:19
@nizarsq On this page I found many fonts has Uyghur specific variants for ۇ and ھ:
http://www.ukij.org/fonts/

I also found following resources that you can see some Uyghur specific variants:
http://www.uyghurdictionary.org/excerpts/Waris_Abdukerim_Janbaz_IUC30.pdf
http://ug.wikipedia.org/wiki/%DA%BE%D8%A7%D8%B2%D9%89%D8%B1%D9%82%D9%89_%D8%B2%D8%A7%D9%85%D8%A7%D9%86_%D8%A6%DB%87%D9%8A%D8%BA%DB%87%D8%B1_%D9%8A%DB%90%D8%B2%D9%89%D9%82%D9%89

**Comment by nizarsq** [comment] 2016-10-25 17:54
@jungshik I test some cases @KrasnayaPloshchad reported on iOS and Windows using different browsers. and noticed Noto Arabic Naskh shape is same on both OS, I tested different Naskh font and noticed differences in shaping for U+0645 and (Sheddah and kasrah) which it behave as @KrasnayaPloshchad mentioned in the bug. attached some screenshots . I will use Harfbuzz as soon I solve the problem with running it on my device. I am assigning this bug to @marekjez86 for further investigation.

Thanks
![os windows browser ie chrome](https://cloud.githubusercontent.com/assets/22158882/19697521/8c14e970-9aa0-11e6-98c8-bb113693785f.png)
![os windows browser ie chrome](https://cloud.githubusercontent.com/assets/22158882/19697524/8f626580-9aa0-11e6-8cef-bb44fb84ab6b.png)
![code](https://cloud.githubusercontent.com/assets/22158882/19697532/935a10b6-9aa0-11e6-9bd8-d1d4a9c14844.png)

**Comment by khaledhosny** [comment] 2016-10-29 16:31
Are all these variants really required? The heh ones in particular look bogus to me as they emulate already separately encoded characters. The meem and mark placement ones are stylistic choice even in Arabic and I have not seen any evidence for language-specific behavior here.

**Comment by KrasnayaPloshchad** [comment] 2016-10-29 16:36
I think Uyghur styled  ۇ/ھ is necesary, when you go to Xinjiang you can see them everywhere.

**Comment by KrasnayaPloshchad** [comment] 2016-10-29 16:44
The SIL’s sample is found at SIL Scheherazade website, I don’t how does SIL discovered them, but I can sure Uyghur specific design that I have been specified because I have found they can be seen everywhere in Xinjiang.

**Comment by khaledhosny** [comment] 2016-10-29 18:44
Agree about ۇ, looks like almost all native Uyghur fonts use an inverted comma instead of the damma, but I don’t see any special ھ behavior.

**Comment by KrasnayaPloshchad** [comment] 2016-10-30 14:50
@khaledhosny I agree with you. Recently I have found that Uyghurs doesn’t receive Middle East styled fonts. I found an example from [an article](http://www.typeisbeautiful.com/2016/02/9927/zh-hant/) of the blog _Type is Baeutiful_. Here is some summaries:

> 2009 年的夏天，在我的朋友古麗米熱（Gülmire M.）的協助下，我將 Frutiger Arabic 展示給 50 名浙江大學的維吾爾大學生，49 名學生都覺得 Frutiger Arabic 怪異且略顯滑稽。如果將現有的機場指示牌上的字體換成更利於視覺閱讀的 Frutiger Arabic，照理說肯定會出彩，因為 Frutiger 本身就是一款經典的導示系統字體，其阿拉伯文版本必然是繼承了這一點，至少很多發達的中東大都市已經用上了它。但可以肯定的是，在烏魯木齊這個做法會遭到極大的抵制。總的來說，維吾爾人並不認同其它地方的現代阿拉伯文字體。

_In summer 2009, with the help of my friend Gülmire M., I shown Frutiger Arabic to 50 Uyghur students of Zhejiang University, 49 of them felt Frutiger Arabic is odd and a bit funny. If replacing typeface of the whole airport signs as Frutiger Arabic which better for reading, it should be better, because Frutiger itself is typical font used for signing system, and being inherited by its Arabic version, at least it has been used by many developed cities of Middle East. BUT one thing is certain, this action would get largely boycotts in Urumqi. Totally, Uyghurs does not receive Arabic come from other places._

> 現在讓我們回到生活中來。有一個現象，大家出去吃飯的時候，經常分不清哪家是新疆維吾爾餐廳，哪家又是別的清真餐廳。因為大多的餐廳都有幾個阿拉伯文字做標牌，誰也看不懂。其實這個很好辦，只要看門頭上的字體就可以了。總的來說，新疆餐廳的字體都是 1982 年後的那種印刷體，橫平豎直、端端正正；而回族餐廳的阿拉伯文，多選擇跳躍性強的手寫風格體。現代的阿拉伯字體，這二者都不會選用，反而在廣州的一些由阿拉伯人經營的餐廳才能看到。

_Let’s go back to life. One phenomenon is, when everybody go to diet, generally hard to distinct which is Xinjiang Uyghur restaurant, which is another Halal restaurant. Because many of them has some Arabic text in signboard, everyone cannot read. Infect it’s easy to do, just seem from its typeface. In general, many Xinjiang restaurants’ typeface is 1982 styled printing typeface, straightly and regularly; but Huizu restaurants’ Arabic text usually uses heavy cursived calligraphic typeface. Both of them are not be used by Arabs’ restaurants in Guangzhou, instead is modernized Arabic typeface._

Later I found these differents several times in Xinjiang, especially ۇ. Thus I think to make Noto Arabic Naskh being accepted by many people written in Arabic script, adding more localized glyphs is necessary.

**Comment by KrasnayaPloshchad** [comment] 2016-11-02 18:29
Kazakh also has the same variant for ۇ as Uyghur used.
https://commons.wikimedia.org/wiki/File:Kazakh_latin_alphabet_(1924).JPG
https://commons.wikimedia.org/wiki/File:Kazakh_latin_alphabet_(1931).JPG

**Comment by jungshik** [comment] 2016-11-28 23:40
@KrasnayaPloshchad , 
> many Xinjiang restaurants’ typeface is 1982 styled printing typeface, straightly and regularlyy; but Huizu restaurants’ Arabic text usually uses heavy cursived calligraphic typeface.

Would  Uyghur speakers in Xinjiang like Noto Arabic Kufic better than Noto Arabic Naskh?

**Comment by KrasnayaPloshchad** [comment] 2016-11-29 03:37
@jungshik I don’t know, but I have seen a few shop signs uses Kufic styled font for Uyghur, even so I still seen localized forms. You can also see the sample on [UKIJ](http://www.ukij.org/fonts/) website, this is sponsored by Xinjiang University, some of fonts looks very similar to what I have seen in there.

**Comment by KrasnayaPloshchad** [comment] 2016-11-29 03:44
On [this article](https://kk.wikipedia.org/wiki/%D2%9A%D0%B0%D0%B7%D0%B0%D2%9B_%D3%99%D0%BB%D1%96%D0%BF%D0%B1%D0%B8%D1%96) I found Kazakh Wikipedians also try to use an Uyghur styled font to render their own Arabic alphabet.

**Comment by KrasnayaPloshchad** [comment] 2017-01-05 16:45
> Do you have an example of a font that have language specific variants?

I have found an online test page including Uyghur specific variants.
http://efont.foundertype.com/fontcompare/ww/efont.htm

**Closed** 2021-01-29 07:48 UTC
Labels: Script-Arabic, in-evaluation
