### ISSUE TITLE
No uppercase Old Hungarian ligatures

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1364] opened 2018-10-31 23:08 UTC
### Font
NotoSansOldHungarian-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansOldHungarian-Regular.ttf
Date: 2018-10-31

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Ligatures are only available for lowercase letters.

### Character data
𐲓‍𐲮𐳓‍𐳮
U+10C93 OLD HUNGARIAN CAPITAL LETTER EK
U+200D ZERO WIDTH JOINER
U+10CAE OLD HUNGARIAN CAPITAL LETTER EV
U+10CD3 OLD HUNGARIAN SMALL LETTER EK
U+200D ZERO WIDTH JOINER
U+10CEE OLD HUNGARIAN SMALL LETTER EV

### Screenshot
![𐲓‍𐲮𐳓‍𐳮](https://user-images.githubusercontent.com/1124347/47823546-32d07300-dd3f-11e8-8667-d04f9ca95d84.png)

**Comment by Kixidevel** [comment] 2019-03-02 05:54
There is a must to keep opened this Issue?

**Comment by Kixidevel** [comment] 2019-03-02 11:27
@dscorbett 
There is a must to be opened this Issue?

**Comment by dscorbett** [comment] 2019-03-03 02:32
What does that mean?

**Comment by Kixidevel** [comment] 2019-03-03 10:08
@dscorbett 
Is it resolved, will be resolved, or never will be resolved?
If it fixed, or never will be fixed, please close. If it will be fixed, don't close.
@marekjez86 ?

**Comment by Kixidevel** [comment] 2019-03-03 10:12
@dscorbett 
I don't remember, that Old Hungarian Q letter exists in UNICODE standard.

**Comment by Kixidevel** [comment] 2019-03-05 02:21
@dscorbett 
I think, @marekjez86 fixed the bugs.

**Comment by Kixidevel** [comment] 2019-03-08 07:02
@dscorbett 
Close this Issue, and forget the letter Old Hungarian Q or Kv, Please! It doesn't existed during the history.
Forget please the ligatures, these are ad-hoc letters.

**Comment by Kixidevel** [comment] 2019-03-08 07:05
Ups! I wrote "doesn't existed" instead of " "did not exist"

**Comment by Kixidevel** [comment] 2019-07-05 07:18
@dscorbett 
Ligatures in Old Hungarian letters are not standardized in UNICODE. Making ligatures on hand-made text is possible, but it can increase the variants of glyphs used on PC. 
For example an  Old Hungarian letter can be a full surname. 
Old Hungarian letters, as its name means, user for Hungarian text. 
Letter Q is wasn't used during the history as a Old Hungarian letter, because Latin texts were used only f.e. by lawyers or  texts of bills.
I am developing a spellchecker, non Hungarian words I am accepting  written Latin letters, as in f.e. Arabic text do.
Did you heard f.e. Cyrillic letter Q?
I think, this issue need to be closed.
Thanks.

**Comment by Kixidevel** [comment] 2019-07-06 09:01
@marekjez86 
Please read my comment above, and close it if you have rigths for.

**Comment by Kixidevel** [comment] 2019-10-01 07:35
@dscorbett 
@marekjez86 
I opened your font below, and opened a ligature property page.
https://github.com/googlefonts/noto-fonts/blob/master/hinted/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
![screenshot_ligature_property](https://user-images.githubusercontent.com/32356899/65942495-b00fd680-e42d-11e9-87f5-2b88cec236bd.jpg)
On the screenshot you can see, that I talked about: However the ligatures are named, no legal code point assigned to. When in a font a character does not linked to a code point, invisible that character. It visible only editing phase.
If you don't believe me, that's your mistake.

**Comment by Kixidevel** [comment] 2019-10-01 12:33
@dscorbett 
@marekjez86 
I wouldn't like that you work unnecessary

**Comment by Kixidevel** [comment] 2020-07-02 09:34
@marekjez86 @dscorbett @google-admin 
I resolve this issue. I will working on uppercase ligatures, but I won't add automatic ligature definitions, because that makes spelling problems. See issue #1776

**Comment by Kixidevel** [comment] 2020-09-29 12:03
@dscorbett 
@marekjez86 
I wrote before I resolve it. But I can't. I do not understand this kind of source code style.

**Comment by dscorbett** [comment] 2020-11-18 18:10
See #1913 for a subset of this issue.

**Comment by Kixidevel** [comment] 2020-11-23 19:17
@nizarsq Nizar, could you do this modifications, too? The issue #1913 is a subset of this issue, as David signed.

**Comment by Kixidevel** [comment] 2020-11-23 19:20
@dscorbett @marekjez86 David, Marek, first I didn't know how do ligatures work. Now I understand. So I'm sorry.

**Comment by Kixidevel** [comment] 2020-11-28 06:11
@nizarsq Nizar, you promissed before, you will resolve #1913 . The Issue #1913 is a subset of this Issue.
We, with @dscorbett waiting for you!

**Comment by acszoltan** [comment] 2020-11-28 10:31
@nizarsq Nizar,  I'm waiting for you to resolve this issue or, at least issue #1913 ,too! If you will or will not to do this modifications in the near future,  please drop me a quick response for this comment.

**Comment by acszoltan** [comment] 2020-11-28 15:41
@marekjez86 
Could it get higher priority? It was opened on november 1 2018 . More than two years ago. Using ligatures without those capital version quite unconfortable, I think.

**Comment by Kixidevel** [comment] 2020-12-01 09:41
@nizarsq Nizar, you don't need to do anything, one of my friends working on it. He can work quickly.

**Comment by acszoltan** [comment] 2020-12-02 08:35
@Kixidevel Could your friend wait, until I finish the repair the issue #1925 ? I think about that, the text is jumping during typing.

**Comment by acszoltan** [comment] 2020-12-02 10:00
@Kixidevel It isn't a good idea to upload an another person's work in your fork, I think.
Were you thinking about this before?

**Comment by acszoltan** [comment] 2020-12-02 10:00
@Kixidevel It isn't a good idea to upload an another person's work in your fork, I think.
Were you thinking about this before?

**Comment by acszoltan** [comment] 2020-12-04 17:27
@marekjez86 @dscorbett @google-admin @brawer 
The problem isn't that, Noto-fonts adopt ligatures or doesn't do that. In Old Hungarian texts using ligatures is only possibilities, not requirements. There are some basic ligatures, that are missing. For example ligature "el" exists, but ligature "él" ("he/she lives") doesn't exist. The combination of ligatures depends on the user's imagination. Somebody wrote me they planned 60 ligatures  Somebody wrote me, he has a ligature database with about 300 ligatures.
My question is:  Noto fonts really needs incomplete basic ligatures, or needs a ligature "boom"?

**Comment by acszoltan** [comment] 2020-12-05 10:44
@dscorbett David, there are lots of ligatures, thats missing, for example "lo" exists (it doesn't means anything itself), but "ló" ("horse") missing. Missing "ti" (plural form of "you") "te" (singular form of "you") "mi" ("we") etc. Letter-like "qu", "x", "w"  ligatures exist for foreign words, but letter-like ligature "y" for foreign words doesn't exist.

Géza Ferenci archaelogist, historian, museum director wrote, that talking about historical Old Hungarian scripts until 1802. year.

Finally, Until 1802 in Old Hungarian texts didn't use ligatures, like "qu", "x" and letters "y" and "w".

**Comment by acszoltan** [comment] 2020-12-05 12:42
@dscorbett 
Here is the correct for, of ligature "ló" :
![Ligature Old Hungarian word "ló"](https://user-images.githubusercontent.com/75157441/101243154-8bcd1b00-36fe-11eb-9273-392c1c2a14b1.jpg)

In the Old Hungarian text, written without ligatures the following "ligatures" replaceable: "w" to "v","x" to "k"+"sz", "qu" to "k"+"v", "y"to "j" or "i" (the "y" transformation depending on the word), as LibreOffice's modern Latin based Hungarian to Old Hungarian translator do!

**Comment by acszoltan** [comment] 2020-12-05 14:44
@marekjez86 Marek,  I must to create all variants of a vowel paired with a consonant, and a consonant paired to a vowel, or I must to do halwork?

**Comment by tamasbartos** [comment] 2021-01-29 05:18
@dscorbett András Tisza's opinion that no ligatures required unless we include all useful ligatures.

**Comment by tamasbartos** [comment] 2021-02-12 17:32
@dscorbett Neither Unicode standard, nor Interrnational nor Hungarian National standards  do not contain Old Hungarian ligatures. International standard is "ISO/IEC 10646:2020" , Hungarian National standard is "MSZ ISO/IEC 10646:2018"  (I have no rights to publish the International and Hungarian National standards' contents )

**Comment by robihorvath** [comment] 2021-03-03 09:14
@dscorbett Do you think about full capital ligatures (all members are capital) or semi-capital ligatures (first letter is capital, the other is low-letters). I think about for example "csin" (ecs+i+en) ligature.

**Comment by dscorbett** [comment] 2021-03-03 19:11
I’ve submitted feedback to Unicode asking for clarification.

**Comment by robihorvath** [comment] 2021-03-05 20:09
@dscorbett  In my opinion is that, semi-capital ligatures are better choice, if we want to use the them in begining of a sentence, but that's true, it wasn't used on that way during the history. Full-capital ligatures would be useful, when we want to use  abbreviations.The last idea is not a good idea, because of that the abbrevations' letter-members (like MTA) means different words (Magyar Tudományos Akadémia.)
So it would be better choice semi-capital ligatures.

**Comment by robihorvath** [comment] 2021-03-16 08:08
> I’ve submitted feedback to Unicode asking for clarification.

@dscorbett  You are misled again! There are no Unicode document are written about capital ligatures! Unicode never will be answer your feedback!

**Comment by robihorvath** [comment] 2021-03-16 08:37
> I’ve submitted feedback to Unicode asking for clarification.

Moreover, if this issue was requested by the Hungarian users I am thinking of, they will not respond. There is an app on "Google play" that they can use make money. The "developers" name  is "Tortabevonó". Their target is that, Noto Old Hungarian font will be made as later as possible. I think they requested issue #1374 . That was the reason, that Noto Old Hungarian UI was developed: an useable Old Hungarian font, which Unicode conform, and that would be closed quickly.

**Comment by rovasinfo** [comment] 2021-04-04 19:40
These ligatures are requested by the Hungarian community, as you can see on this agreement.

![agreement 2009p0 p257](https://user-images.githubusercontent.com/81823602/113519714-46c2d380-958e-11eb-96f9-7ceed26f4596.jpg)

![agreement 2009p2](https://user-images.githubusercontent.com/81823602/113519506-f72fd800-958c-11eb-9490-3edeabdd1b53.jpg)

Source: ISBN 978-963-87967-5-2  p257, 259

**Closed** 2021-04-12 19:36 UTC
Labels: Script-OldHungarian
