### ISSUE TITLE
Misplacement of upper stroke of U+06AF in Noto Nastaliq Urdu Bold

### ISSUE THREAD

**Issue by Etewilak** [googlefonts/noto-fonts#2243] opened 2022-02-06 11:54 UTC
The upper stroke of U+06AF is Noto Nastaliq Urdu Bold is sometimes misplaced.
The following is an image of an example:
![image](https://user-images.githubusercontent.com/55674356/152679558-ddf785da-ce45-4e2a-9a38-09bc438c568f.png)

**Comment by simoncozens** [comment] 2022-02-06 14:25
This is a duplicate of #2231, which is now fixed in the sources and new builds.

**Closed by simoncozens** 2022-02-06 14:25 UTC
