### ISSUE TITLE
Bad anchor points on spacing Greek diacritics

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1223] opened 2018-06-16 13:46 UTC
### Font
NotoSans-Regular.ttf
NotoSansMono-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-05-31

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The spacing diacritics in Greek Extended should not have anchor points.

### Character data
α᾽α᾿α῀α῁α῍α῎α῏α῝α῞α῟α῭α΅α`α´α῾
U+03B1 GREEK SMALL LETTER ALPHA
U+1FBD GREEK KORONIS
U+03B1 GREEK SMALL LETTER ALPHA
U+1FBF GREEK PSILI
U+03B1 GREEK SMALL LETTER ALPHA
U+1FC0 GREEK PERISPOMENI
U+03B1 GREEK SMALL LETTER ALPHA
U+1FC1 GREEK DIALYTIKA AND PERISPOMENI
U+03B1 GREEK SMALL LETTER ALPHA
U+1FCD GREEK PSILI AND VARIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FCE GREEK PSILI AND OXIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FCF GREEK PSILI AND PERISPOMENI
U+03B1 GREEK SMALL LETTER ALPHA
U+1FDD GREEK DASIA AND VARIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FDE GREEK DASIA AND OXIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FDF GREEK DASIA AND PERISPOMENI
U+03B1 GREEK SMALL LETTER ALPHA
U+1FED GREEK DIALYTIKA AND VARIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FEE GREEK DIALYTIKA AND OXIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FEF GREEK VARIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FFD GREEK OXIA
U+03B1 GREEK SMALL LETTER ALPHA
U+1FFE GREEK DASIA

### Screenshot
![α᾽α᾿α῀α῁α῍α῎α῏α῝α῞α῟α῭α΅α`α´α῾](https://user-images.githubusercontent.com/1124347/41499199-f62f0a3a-7149-11e8-8a26-19435ad8a8c6.png)
![α᾽α᾿α῀α῁α῍α῎α῏α῝α῞α῟α῭α΅α`α´α῾](https://user-images.githubusercontent.com/1124347/41499201-f6517480-7149-11e8-9f7b-3f66afad1a69.png)
![α᾽α᾿α῀α῁α῍α῎α῏α῝α῞α῟α῭α΅α`α´α῾](https://user-images.githubusercontent.com/1124347/41499200-f641a758-7149-11e8-8142-bbb309be0db0.png)

**Comment by anthrotype** [comment] 2018-06-18 10:10
Thanks for the report. I suspect this has to do with the automatic "anchor propagation" feature in glyphsLib, which automatically copies anchors from a component's base glyph to the composite glyphs using them.
The spacing Greek diacritics probably share the same outline as the combining non-spacing diacritics, e.g. the former are "composite" glyphs that include the latter as components. So the anchor points of the latter get automatically copied to the former. And when the ufo2ft MarkFeatureWriter generates the mark/mkmk features, it sees that those glyphs contain attaching anchors and thus includes them in the mark/mkmk features.

There is an open issue in glyphsLib repo where we are discussing about modifying or disabling this feature:
https://github.com/googlei18n/glyphsLib/issues/368

**Comment by anthrotype** [comment] 2018-06-18 10:27
actually, I take that back. I checked NotoSans-MM.glyphs source, and it looks like the spacing diactritic glyphs mentioned by the OP all have a `_top` anchor defined. It's not because they are composite glyphs and as such automatically inherit anchors from their component; rather the designer manually added anchors to them.

Maye we'll have to rethink the way our MarkFeatureWriter decides whether a glyph is to be considered a combining mark or not. Glyphs.app uses its own GlyphData.xml database, with hardcoded glyph names mapping to some Unicode properties and predefined list of anchor names. In ufo2ft, we simply check for the presence of an underscore-prefixed anchor, e.g. "_top", and if that has some corresponding anchor named "top" anywhere else in the font, we automaticaly consider that glyph a combining mark.
I'll open an issue on the ufo2ft repository.

**Comment by nizarsq** [comment] 2020-07-10 23:12
<img width="614" alt="Screen Shot 2020-07-10 at 4 12 32 PM" src="https://user-images.githubusercontent.com/22158882/87209818-2ba98880-c2c8-11ea-98bd-18b70dbc7076.png">

**Comment by moyogo** [comment] 2021-04-11 04:56
Confirmed fixed with build made after fontmake was updated with googlefonts/ufo2ft #276.

**Closed by moyogo** 2021-04-11 04:56 UTC
Labels: Script-LatinGreekCyrillic, Script-Monospace, in-evaluation
