### ISSUE TITLE
Mispositioned marks on extraneous “Allah” ligature

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1588] opened 2019-10-12 14:14 UTC
### Font
NotoNastaliqUrdu-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/e87ac4b84ac38f7cff7fd6d87918d45785c0e9ea/phaseIII_only/unhinted/otf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.otf
Date: 2019-10-11

### Font version
Version 2.000

### Issue
The “Allah” ligature of the sequence lam–lam–heh is formed even when some of the letters have marks that are not positioned properly on the resulting ligature. The ligature should probably only be formed for the basic letters and not all letters that share their joining groups.

### Character data
ݪلَۃ
U+076A ARABIC LETTER LAM WITH BAR
U+0644 ARABIC LETTER LAM
U+064E ARABIC FATHA
U+06C3 ARABIC LETTER TEH MARBUTA GOAL

### Screenshot
![ݪلَۃ](https://user-images.githubusercontent.com/1124347/66702667-0c99ae00-ecd8-11e9-8056-ea67b785677a.png)

**Comment by nizarsq** [comment] 2020-05-24 01:13
This issue still reproducible
<img width="405" alt="Screen Shot 2020-05-23 at 6 10 49 PM" src="https://user-images.githubusercontent.com/22158882/82743485-1761fa00-9d21-11ea-8fea-3d5f8ca05fe3.png">

**Comment by nizarsq** [comment] 2020-09-23 02:57
Revisiting this issue to look into the issue itself.
Let me start with some clarification:
1- The combination provided is not Allah(God) it is Llah (For god) (this is just a note)
2- Assuming we are looking to write Llah or Allah,  U+076A ARABIC LETTER LAM WITH BAR is wrong character to use, it should use U+ 0644 ARABIC LETTER LAM (ل)
3- Same thing for U+06C3 ARABIC LETTER TEH MARBUTA GOAL. this is wrong character, Allah(God) or Llah (For god)  should use U+0647 ARABIC LETTER HEH instead of using U+06C3

The take out is, using wrong letters will cause lookup for forming issue for this ligature. @marekjez86 for second opinion/closing the bug
Characters data:
اللَه للَه
اݪلَۃ ݪلَۃ
الله لله

<img width="1421" alt="Screen Shot 2020-09-22 at 7 54 20 PM" src="https://user-images.githubusercontent.com/22158882/93959394-69398180-fd0d-11ea-9ae9-47f2ce392203.png">

**Comment by dscorbett** [comment] 2020-09-23 20:54
>Assuming we are looking to write Llah or Allah

Why do you assume that? If I were trying to write those words, I would have used different code points. Please reopen this.

**Comment by marekjez86** [comment] 2020-09-24 00:39
@dscorbett @nizarsq : thank you for your comments.
@dscorbett : "Why do you assume that?" I assumed that you want to write that because of the title you gave to the issue. Did you mis-write the title?

@nizarsq : please do not change anything yet, until we finish discussing if a font needs to support any text (including ones that are NOT relevant to any living or dead languages). Once we answer this question, we'll take more actions. Until that time please let's leave it as is.

**Comment by marekjez86** [comment] 2020-09-24 01:52
@anthrotype @behdad @davelab6  @kenlunde @khaledhosny @kmansourMT @moyogo @punchcutter  @roozbehp @rsheeter @SteveMatteson @tiroj @thundernixon @twardoch : Dear Friends + Family of Noto, I'm using this issue and this comment to help us decide what we should do when maintaining a font. This particular issue was raised about a text fragment that doesn't appear anywhere on the web indexed by Google. I have recommended to @nizarsq to close the issue thinking that is not relevant to any native reader or writer of any language using Arabic script (hence we will not deal with it). We also have a limited amount of money to fix issues and this wouldn't appear on any of my priority list. @dscorbett who is the most prolific (BIG THANKS!) Noto issue finder feels differently, hence I'm seeking your advice. I wanted to ask you, as much more experienced than I am in the font business, for an opinion. Would you want to know this type of information about your font or tool? Or would you consider it as something that you wouldn't act upon? Note that I think of creating a github tag for closed issues which were evaluated and considered as "WillNotBeFixed" (to identify the issues that were closed but not fixed) or "TestTextNotFoundOnWeb" (or something like this) if we keep this type of issue open. Any and all ideas/opinions are welcome... Please help decide... Would you take time to fix this type of issue in the font (or harfbuzz or wherever)? I intend to "listen" to the results of this discussion (assuming we have the money :-)) On one hand all of the open issues define the complete "state" of a font. And it's good to know the state. On the other hand I don't want us to continue multiple times evaluate "fix/not fix" open issues for issues that IMHO will not be fixed ---- Thanks a lot for your feedback. Marek. PS. If you value somebody's opinion feel free to invite them to contribute :-)

**Comment by davelab6** [comment] 2020-09-24 03:22
@marekjez86 said,

> "Why do you assume that?" I assumed that you want to write that because of the title you gave to the issue. Did you mis-write the title?

Kindly, the title is, emphasis mine, "Mispositioned marks on **extraneous** “Allah” ligature"

So what I understand @dscorbett to be saying is that when he writes the sequence `U+076A U+0644 U+064E U+06C3` then he gets a ligature which is extraneous - unexpected - and, worse, the marks are not positioned correctly.

So when @nizarsq says,

> Assuming we are looking to write Llah or Allah

I think @dscorbett is fair to say that assumption is not relevant. If it was, then,

> using wrong letters will cause lookup for forming issue for this ligature

would be a fair conclusion, but the ligature is not desirable.

Still, to debug, it would be helpful to have some words in which these 4 characters occur; it seems that by themselves they do not occur as a word, but presumably @dscorbett is writing something with them. What are these somethings, David? :)

**Comment by marekjez86** [comment] 2020-09-24 04:29
@behdad

**Comment by khaledhosny** [comment] 2020-09-24 06:28
The ligature is wrong here and should not be formed for this sequence of characters (regardless if it is a sequence of characters forming a real word or not, that is besides the point). It can even be seen as religiously insulting by some, since the [A]llah ligature is reserved only to the name of God and is never used for any other word.

Fonts should generally be conservative when forming this ligature since false positives are problematic. False negatives can be tolerated, but probably not for a traditional style like this, so need not be too conservative.

In calligraphy and traditional typesetting, the calligrapher/typesetter would chose the ligature or not based on the meaning of the text, but controlling ligatures in computer typography has a very bad UX/not even possible in many situations, so many computer fonts (especially ones with more traditional styles) opt for making this ligature automatically, but this leads to issue like we have here so more thought is often needed.

**Comment by marekjez86** [comment] 2020-09-24 06:37
@khaledhosny : thank you very much for the generous gift of feedback. Dave reopened the issue.

**Comment by marekjez86** [comment] 2020-09-24 06:56
ݪلَۃ samples from fonts.google.com (some of them show tofu :-))
<img width="1177" alt="Screen Shot 2020-09-23 at 23 54 04" src="https://user-images.githubusercontent.com/13322623/94111012-518af780-fdf8-11ea-8af7-5cc3061fecfa.png">

**Comment by marekjez86** [comment] 2020-09-24 06:57
sample of fonts on my Mac

<img width="439" alt="Screen Shot 2020-09-23 at 23 51 03" src="https://user-images.githubusercontent.com/13322623/94111147-85661d00-fdf8-11ea-9559-6778aaba5cec.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 50 43" src="https://user-images.githubusercontent.com/13322623/94111151-87c87700-fdf8-11ea-9c8d-6cf3cdf7ff33.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 50 32" src="https://user-images.githubusercontent.com/13322623/94111154-88610d80-fdf8-11ea-8ed7-aeec810c57b9.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 48 48" src="https://user-images.githubusercontent.com/13322623/94111157-88f9a400-fdf8-11ea-8fc6-4faa7cd6f376.png">
![Uploading Screen Shot 2020-09-23 at 23.48.41.png…]()

**Comment by marekjez86** [comment] 2020-09-24 06:58
<img width="439" alt="Screen Shot 2020-09-23 at 23 48 22" src="https://user-images.githubusercontent.com/13322623/94111163-8a2ad100-fdf8-11ea-9f40-02c0026f7cd8.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 48 05" src="https://user-images.githubusercontent.com/13322623/94111165-8ac36780-fdf8-11ea-88aa-7fbf737e56cf.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 47 48" src="https://user-images.githubusercontent.com/13322623/94111166-8ac36780-fdf8-11ea-826a-79d31b0ec977.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 47 07" src="https://user-images.githubusercontent.com/13322623/94111169-8b5bfe00-fdf8-11ea-827e-353c4842ba11.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 46 58" src="https://user-images.githubusercontent.com/13322623/94111170-8b5bfe00-fdf8-11ea-9842-a266352afc03.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 46 25" src="https://user-images.githubusercontent.com/13322623/94111174-8bf49480-fdf8-11ea-8893-0b95340fa82b.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 46 16" src="https://user-images.githubusercontent.com/13322623/94111175-8bf49480-fdf8-11ea-8a9d-662a0c721b70.png">
<img width="439" alt="Screen Shot 2020-09-23 at 23 45 59" src="https://user-images.githubusercontent.com/13322623/94111176-8bf49480-fdf8-11ea-8598-c8dfc93a0382.png">

**Comment by nizarsq** [comment] 2020-09-24 07:24
> Revisiting this issue to look into the issue itself.
> Let me start with some clarification:
> 1- The combination provided is not Allah(God) it is Llah (For god) (this is just a note)
> 2- Assuming we are looking to write Llah or Allah, U+076A ARABIC LETTER LAM WITH BAR is wrong character to use, it should use U+ 0644 ARABIC LETTER LAM (ل)
> 3- Same thing for U+06C3 ARABIC LETTER TEH MARBUTA GOAL. this is wrong character, Allah(God) or Llah (For god) should use U+0647 ARABIC LETTER HEH instead of using U+06C3
> 
> The take out is, using wrong letters will cause lookup for forming issue for this ligature. @marekjez86 for second opinion/closing the bug
> Characters data:
> اللَه للَه
> اݪلَۃ ݪلَۃ
> الله لله
> 
> <img alt="Screen Shot 2020-09-22 at 7 54 20 PM" width="1421" src="https://user-images.githubusercontent.com/22158882/93959394-69398180-fd0d-11ea-9ae9-47f2ce392203.png">

@khaledhosny I agree with you this sequence of characters should not be formed, NotoNastaliqUrdu currently does not form it. See the difference in. rendering when the correct sequence used (الله لله) vs the wrong sequence (اݪلَۃ ݪلَۃ) in test case I attached previously.

**Comment by marekjez86** [comment] 2020-09-24 07:32
popular  Urdu font

<img width="430" alt="Screen Shot 2020-09-24 at 00 31 51" src="https://user-images.githubusercontent.com/13322623/94114627-75047100-fdfd-11ea-8b83-6d4e26ce3d7e.png">

**Comment by dscorbett** [comment] 2020-09-29 16:58
My original report was not the full explanation. This bug applies to any joining group sequence lam–lam–heh where there is at least one of U+0670, U+064E, or U+0651 between the letters in a few specific patterns (see lookup 13) and there are no other intervening marks, whether diacritics or ijam, except for `Crossbar`. It’s just that single mark that is missing from the mark class. That is why I reported it: even if no one can find an attestation, it takes two seconds to fix, so why not fix it?

The second part of the bug is slightly less trivial to fix. The heh must not have any ijam after it. One way to do this is to add substitution rules that match these patterns plus ijam, which, if matched, do nothing. This affects U+0629, U+06C0, U+06C2, and U+06C3.

Also, U+06D5 ARABIC LETTER AE should not be allowed in this sequence either, even though it has no ijam. One way to fix this is to not merge the glyphs for U+06D5 and U+0647 ARABIC LETTER HEH before this lookup.

I have looked but have not been able to find an attestation of this sequence. Gawri a.k.a. Kalami seemed promising but I was not able to find a corpus of sufficient size. That is the problem with bugs pertaining to low-resource languages: it is hard to discover whether a bug is a real problem or not. I think it is better to err on the side of fixing them, especially when it is easy to do.

**Comment by simoncozens** [comment] 2022-01-27 11:21
I understand @dscorbett to be making a general point here - *any* "non-standard" sequence of l-l-h is getting substituted for the divine name ligature, which is clearly a mistake. Even if the specific sequence of marks he provided is not attested in any corpus, other combinations will be. I think this is an easy fix anyway - just a matter of chaining the mark filtering set for the ligature formation.

**Comment by tiroj** [comment] 2022-01-27 16:50
Note that there are also language exception issues around formation of the theograph ligature with or without marks. A lot of Arabic script fonts have been made specifically for Arabic language use, in which the sequence lam-lam-heh للە forms the theograph shape—even including the shadda and dagger alif that are not present in the character string:
![image](https://user-images.githubusercontent.com/5614500/151402316-e24316b8-a599-45b4-8825-9bae159ebf7f.png)

This makes such fonts unusable for e.g. Kurdish, in which that sequence of letters may occur in word such as گوللە and  کەللە. So in addition to only forming the theograph ligature in the context of the specific marks that it conventionally carries when part of the divine name—even though this requires Arabic users to input it including those characters and not, as many existing fonts have encouraged, as just lam-lam-heh—, steps could also be taken to limit its formation at all in non-Arabic langsys shaping.

**Comment by simoncozens** [comment] 2022-01-27 17:24
Well, quite. I have noticed that most of the Nastaliq-related issues posted here seem to be due to people trying to use Noto Nastaliq *Urdu* as Noto Quranic Arabic… ;-)

**Closed** 2022-01-27 18:44 UTC
Labels: Script-Arabic, Nastaliq, evaluation-completed

**Comment by r12a** [comment] 2022-01-28 11:06
I think that information about the current language of the text, where available, should also be factored in to whether the ligature fires or not. So text that is labelled Kurdish would not produce the ligature, but text labelled as Arabic might.
