### ISSUE TITLE
AE ARABIC LETTER not joined with what comes before 

### ISSUE THREAD

**Issue by M86xKC** [googlefonts/noto-fonts#1138] opened 2018-04-10 10:23 UTC
https://github.com/googlei18n/noto-source/issues/115

Font: 'NotoSansArabic'
Version: latest

**Comment by marekjez86** [comment] 2018-04-14 14:00
see https://github.com/googlei18n/noto-source/issues/115 for the details

**Comment by nizarsq** [comment] 2018-07-03 18:39
This issue is a duplicate of #1017

**Closed** 2019-05-22 00:40 UTC
Labels: Script-Arabic, Status-Duplicate
