### ISSUE TITLE
Wrong glyph for U+0620 ARABIC LETTER KASHMIRI YEH

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1172] opened 2018-05-06 23:27 UTC
### Font
NotoNastaliqUrdu-Regular.ttf
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Nastaliq Urdu: Version 1.02 uh
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The ring of U+0620 ARABIC LETTER KASHMIRI YEH should not be attached to its rasm.

Additionally, its final form in Noto Nastaliq Urdu does not attach to the preceding glyph properly. Its cursive positioning and contextual forms should be like those of U+06CC ARABIC LETTER FARSI YEH.

### Character data
ؠ
U+0620 ARABIC LETTER KASHMIRI YEH

### Screenshot
![ؠ ؠؠؠ](https://user-images.githubusercontent.com/1124347/39678673-ca419d58-515e-11e8-9f9a-6963814032b7.png)
![ؠ ؠؠؠ](https://user-images.githubusercontent.com/1124347/39678674-ca5b7340-515e-11e8-96b1-fa8f641de92d.png)

**Comment by nizarsq** [comment] 2020-05-30 05:21
Issues reported still reproducible for both fonts with exception to the final position form for U+0620 now fixed (Ring not attached to its rasm).
<img width="1370" alt="Screen Shot 2020-05-29 at 10 10 43 PM" src="https://user-images.githubusercontent.com/22158882/83320243-78467200-a1fa-11ea-8b41-782e42dbddd7.png">
ring not attached to its rasm).

**Comment by nizarsq** [comment] 2020-09-22 07:23
Below are my conclusions based on the current NotoNastaliqUrdu and Arabic fonts. Characters used in the test below: (U+0620, U+0620 U+0644 , U+0644 U+0620 U+0644 , U+0644 U+0620 ). This represents U+0620 in all forms (Stand alone, initial, medial and final ).

1- Attached ring issue is reproducible on NotoSansArabic(initial, medial),  NotoSansArabicUI (All forms), NotoKufiArabic don't have U+0620 in the font, NotoNaskhArabic (All forms) and NotoNastaliqUrdu (initial, medial).

2- Final form in NotoNastaliqUrdu looks ok, Not sure what is the combination used in the screenshot attached in the bug report but the U+0644 U+0620 looks ok.  If U+0620 twice to show the issue with the final form then this is not a valid test since U+0620 used to indicate palatalization and will never come together twice.
<img width="1432" alt="Screen Shot 2020-09-22 at 12 07 53 AM" src="https://user-images.githubusercontent.com/22158882/93852870-acd9b000-fc67-11ea-95c7-89cc20625d99.png">

**Comment by dscorbett** [comment] 2020-09-22 13:17
You shouldn’t be so focused on attestations when faced with an obvious bug, but fine: here’s an example of this bug in “مٕتؠ”, a bona fide Kashmiri morpheme [sourced directly from Wikipedia](https://en.wikipedia.org/w/index.php?title=Kashmiri_language&oldid=978968132#Aspect).
![مٕتؠ](https://user-images.githubusercontent.com/1124347/93885867-b6d4d080-fcb2-11ea-838b-3c608353c564.png)

**Comment by r12a** [comment] 2020-09-22 14:47
Slightly off topic, and maybe needed separate issues unless there's a quick answer: @dscorbett the shape of the hamza in your example suggests to me that you have tagged the text as Urdu, rather than Kashmiri (which produces a rounded hamza for me). That catches by the tail the larger question of whether we should be using a font named 'Urdu' for Kashmiri.  Unless this is answerable quickly in this thread, i should probably start a new one, but has this been discussed somewhere already, and is there documentation somewhere for available font features in Noto fonts (along the lines of https://software.sil.org/scheherazade/wp-content/uploads/sites/29/2016/03/Scheherazade-features-2.100.pdf)?

**Comment by dscorbett** [comment] 2020-09-22 15:27
I didn’t tag the text as anything; that is just the default glyph for U+0655 in this font. Anyway, this bug report is about U+0620, so let’s discuss hamzah glyphs and language support in a new one.

**Comment by nizarsq** [comment] 2020-09-22 18:17
I don’t think this is an obvious bug. The following circumstances should met to reproduce it:
1- U+0620 should be final form “half yeh” variant
2- Preceded character should be one of these characters U+0628,U+067E,U+062A,U+0679,U+062B
3- Preceded character (U+0628,U+067E,U+062A,U+0679,U+062B) should be in the medial form
Script used in this test: 
&#1578;&#1568; &#1576;&#1568; &#1662;&#1568; &#1579;&#1568; &#1740;&#1568; &#1657;&#1568; &#1606;&#1568;

&#1605;&#1578;&#1568; &#1605;&#1576;&#1568; &#1605;&#1662;&#1568; &#1605;&#1579;&#1568; &#1605;&#1740;&#1568; &#1605;&#1657;&#1568; &#1605;&#1606;&#1568;

<img width="725" alt="Screen Shot 2020-09-22 at 11 11 52 AM" src="https://user-images.githubusercontent.com/22158882/93920725-6e261300-fcc4-11ea-8f66-83b83eeafd9f.png">

**Comment by nizarsq** [comment] 2020-11-17 02:53
Adding NotoNaskhArabic to this bug

**Closed** 2020-11-24 06:55 UTC
Labels: Naskh, Nastaliq, Sans, Script-Arabic, in-evaluation, wrong glyph(s)
