### ISSUE TITLE
False form of (ۀ) in Noto Naskh Arabic

### ISSUE THREAD

**Issue by soheilkhanalipur** [googlefonts/noto-fonts#2060] opened 2021-04-08 20:22 UTC
Letter (ۀ) is called "HEH WITH YEH ABOVE", Noto Naskh Arabic displays it as (هٔ | HEH WITH HAMZA ABOVE).

**Comment by moyogo** [comment] 2021-04-08 21:30
This is as intended. ۀ ‎06C0 (ARABIC LETTER HEH WITH YEH ABOVE) is supposed to have a hamza above, as it is equivalent to ۀ ‎06D5 0654 (ARABIC LETTER AE, ARABIC HAMZA ABOVE).

While Unicode uses the name ARABIC LETTER HEH WITH YEH ABOVE for 06C0 it also provides the following information in the [Unicode Arabic Block chart](https://www.unicode.org/charts/PDF/U0600.pdf):
06C0 ۀ ARABIC LETTER HEH WITH YEH ABOVE
- = arabic letter hamzah on ha (1.0)
- for ezafe, use 0654 ◌ٔ over the language-appropriate base letter
- actually a ligature, not an independent letter
- ≣ 06D5 ە‎ 0654 ◌ٔ

This means the following:
- 06C0 was called ARABIC LETTER HAMZAH ON HA in Unicode 1.0
- some languages use other characters that might look the same in some contexts but different in others, like 0647 ARABIC LETTER HEH with 0654 ARABIC HAMZA ABOVE instead of using 06C0.
- 06C0 is canonically equivalent to 06D5 0654 (ARABIC LETTER AE, ARABIC HAMZA ABOVE).

See https://groups.google.com/g/persian-computing/c/RAYzOyhisDs/m/gS2bMDLlYfsJ?pli=1 for a history of 06C0 ARABIC LETTER HEH WITH YEH ABOVE and why it has this name in Unicode.

**Comment by marekjez86** [comment] 2021-04-09 01:00
@nizarsq : please close it (after you read it :-) )

**Comment by nizarsq** [comment] 2021-04-09 01:44
WAI for all Noto fonts. Thanks
<img width="704" alt="Screen Shot 2021-04-08 at 6 43 26 PM" src="https://user-images.githubusercontent.com/22158882/114116870-5007b500-989a-11eb-9914-cd8738e05992.png">

**Closed by nizarsq** 2021-04-09 01:44 UTC
Labels: Script-Arabic, Status-NotABug
