### ISSUE TITLE
Add different weights of Arimo, Tinos and Cousine.

### ISSUE THREAD

**Issue by tankmohit** [googlefonts/noto-fonts#1034] opened 2018-01-15 19:57 UTC
Arimo, Tinos and Cousine are beautiful fonts without a doubt.
I use them on my all machines even on windows. 
It would be great if Google decide to make some weights for those great fonts.

**Comment by KrasnayaPloshchad** [comment] 2018-01-25 15:59
Alternatively, they can be achieved by adding font variations into them.

**Comment by CamelCase11** [comment] 2018-01-25 16:03
Here I forgot to mention that I am talking about thin, light and medium(semibold) weights.

**Comment by CamelCase11** [comment] 2018-01-26 03:13
But what about Tinos and cousine. Cousine is very beautiful font. All it need are different weights.

**Comment by KrasnayaPloshchad** [comment] 2018-01-29 15:11
> Here I forgot to mention that I am talking about thin, light and medium(semibold) weights.

Yes, variable font can do it too.

**Comment by cssobral2013** [comment] 2018-12-26 18:12
@davelab6, Archivo is good but has no Light nor Black weights, so I prefer to wait this issue to be solved.

**Comment by marekjez86** [comment] 2020-08-02 01:11
duplicate of https://github.com/googlefonts/noto-fonts/issues/1081

**Closed by marekjez86** 2020-08-02 01:11 UTC
Labels: Script-LatinGreekCyrillic
