### ISSUE TITLE
Noto Sans Cuneiform not working

### ISSUE THREAD

**Issue by hreyes82** [googlefonts/noto-fonts#2312] opened 2022-04-07 20:42 UTC
NotoSansCuneiform-Regular.ttf
https://fonts.google.com/noto/specimen/Noto+Sans+Cuneiform?noto.query=cunei
2022-04-07
Version Windows 2.000
Issue observed using Microsoft Word

I installed the font as I typically would and when I choose the font to use it, text appears in regular typography not in Cuneiform. I'm using other fonts that do work but this one does not. When I open the downloaded file, the font or typography also displays as regular font not cuneiform. Could this be that the wrong file has been provided?

**Comment by Mercury13** [comment] 2022-04-07 22:26
What characters do you type? This is a Unicode font, so typing Latin letters will do nothing.

https://www.fontspace.com/zarathustra-font-f13841
This font supports both Persian cuneiform (not Sumerian!) 103A0…D5 and also mapped to Latin. Persian cuneiform is alphabet, so it’s possible somehow.

https://fonts.google.com/noto/specimen/Noto+Sans+Cuneiform?noto.query=cunei
This font supports three ranges of Sumerian cuneiform 12000…543, and NOTHING is mapped to Latin. Sumerian cuneiform is hierosyllabic, so there’s no point mapping to Latin. And that’s Unicode font meant to read and write in some language implemented in Unicode, not to make fancy text.

**Comment by hreyes82** [comment] 2022-04-08 01:08
I regular english words that I want to translate to cuneiform...

**Comment by Mercury13** [comment] 2022-04-08 07:26
> I regular english words that I want to translate to cuneiform...
If you are e.g. a tattoo master, you need another font. We are serious people who discuss how glyphs combine to words, how to fix bugs in umlauts when e.g. in Tibetan or Gujarati three of them stick to one letter, how to circumvent faulty typography engines, and if there are still tofu remaining (Noto = No tofu). But first read this post: http://hanzismatter.blogspot.com/2006/08/gibberish-asian-font-mystery-solved.html

**Comment by simoncozens** [comment] 2022-04-08 08:53
Closing this; it's not a bug in the font. Fonts draw text, they don't translate it.

**Closed by simoncozens** 2022-04-08 08:53 UTC

**Comment by hreyes82** [comment] 2022-04-08 13:18
What an answer, very professional, specially whem you argue that you are
serious people. All I asked is for help on how to use a font that did not
worked. I dosnloaded the font and it did not work, that is all, regardless
of what I plan to use it for, communities like this should try to help not
pretend to be so much smarter than other that won't. I downloaded this
google font like I downloaded many others, to use them in creating
cuneiform. They all worked, thia one didn't. That's all.

**Comment by yanone** [comment] 2022-04-08 13:39
@hreyes82

First of all, please note that this is a public forum and anyone can comment on the issue you created. To our knowledge, the user @Mercury13 is not affiliated with Google Fonts and their response should therefore not be mistaken as originating from Google Fonts.

About your problem: 

You seem to expect that you type a Latin character (e.g. `A`) and that the font in question _transcribes_ it to a Cuneiform caracters (e.g. `𒀀`). While certainly fonts exist out there that have this functionality, it is not how fonts on Google Fonts work. Our fonts follow the Unicode standard, a database that is constantly expanding to give every glyph of every script on this planet a code which can be process by machines. The Unicode block for Cuneiforms is described here: https://en.wikipedia.org/wiki/Cuneiform_(Unicode_block)

As you can see, the Cuneiform alphabet is quite different from Latin, and it is therefore not trivial to _translate_ or _transcribe_ Latin into Cuneiform. But it is also not intended. 

The font in question, Noto Sans Cuneiform, and all other fonts on Google Fonts, will output the characters in the respective font design only when you put in the correctly encoded characters. It will print 𒀀 only if you put in `𒀀` in your text editor.

For starters, it may help if you copy/paste individual characters from the Wikipedia page I linked and see if they show up in Noto Sans Cuneiform in the app you're using.

**Comment by hreyes82** [comment] 2022-04-08 14:27
Thank you for your response and clarification @yanone I appreciate t as it helps me better understand how it works. I understand what you are trying to say and that Latin word etc. won't be translated or converted to cuneiform, however, not even individual characters do? There is no character in my keyboard that converts using this font?I have installed some other similar fonts and they all type in cuneiform, character by character, converting each character I type. This one does not, and displayed the text as I type it in English, not even a black square or error, so I wondered if there was something wrong I did when I installed it. If I can check a cuneiform transcription and see how "a" for example would be translated in cuneiform, why is this font displaying "a" in English, instead of the cuneiform?

**Comment by simoncozens** [comment] 2022-04-08 14:52
I'm aware that other fonts may work differently, but this is because those fonts have different objectives. Noto follows a standard of encoding called the Unicode Standard, which defines how characters should be represented to the computer. It allows for different scripts to work together regardless of font. Before Unicode was a standard, people would make up their own encodings for characters; "a" might mean "a" in an English font and "က" in a Burmese font and "𒀀" in a Cuneiform font. *This was a terrible thing!* You changed the font in your document, or you had a different font installed to the person who wrote the document, and the text becomes completely different.

Unicode assigns a single meaning to a single character. If you type the letter "a" you get the letter "a", whatever font you use. And this makes sense - by typing the letter "a", you've just told the computer you want the letter "a", not "𒀀"! In Unicode, Cuneiform letters are encoded in a completely separate "block" to the Latin letters, so there's no confusion. Other fonts which use a "hacked" encoding might make it easier for you to type, but they have a fundamental problem in that they turn a document written Latin letters into something that it is not (Cuneiform letters). So that's why we follow Unicode in this project.

But this means you do have to work a bit harder to input Cuneiform text. To access the Unicode Cuneiform block, you can either install a keyboard which supports those characters, or you can use a character picker such as [UniView](https://r12a.github.io/uniview/) to choose the characters you need.

**Comment by r12a** [comment] 2022-04-08 15:10
> But this means you do have to work a bit harder to input Cuneiform text. To access the Unicode Cuneiform block, you can either install a keyboard which supports those characters, or you can use a character picker such as [UniView](https://r12a.github.io/uniview/) to choose the characters you need.

Hint: To quickly transfer cuneiform from the left panel to the text area, double-click on a character in the left panel, or change the direction of the red arrow in the middle by clicking on it. (I recommend reading the [Help page](https://r12a.github.io/uniview/help) for tips like that.)

Actually, there's little chance it's relevant but there's a [Ugaritic character app](https://r12a.github.io/pickers/ugar/) which makes input much easier still, but is only focused on use of cuneiform for Ugaritic. There is no more general cuneiform character app yet.

hth

**Comment by hreyes82** [comment] 2022-04-08 15:49
Thank you @r12a @simoncozens for your explanations and input, it truly helps too. I guess I made the mistake of thinking that I would just install this font like any other and it would turn characters I was typing into cuneiform. This definitely helps me understand what is going on so thanks. 

How would I be able to get to Sumerian cuneiform? Is there anything out there already put together?

**Comment by twardoch** [comment] 2022-04-08 17:06
To further clarify: if you have a physical keyboard, it doesn’t really matter what letters are printed on it. It matters what _keyboard layout_ you have active in your operating system. Mostly, you choose just one keyboard layout when you install your computer, or the manufacturer has picked one for you.

The default (and often only) keyboard layout is typically associated with the UI language. If your operating system is in English, then your default keyboard layout is possibly U.S. English. 

But you can install (in your System Preferences or Control Panel) additional keyboard layouts. Then in the taskbar you’ll see a switcher for the keyboard layouts. 

If you have the U.S. English and Greek keyboard layouts installed, and the U.S. English layout is active and you press the A key, that key press translates to the Unicode Latin letter »a«, so that letter gets inserted into your text editor. But if you activate the Greek keyboard layout and press A, that gets translated into the Unicode Greek letter alpha, so »α« gets inserted into the text.

Each Unicode writing system and language typically needs its dedicated keyboard layout. Operating systems don’t have have dedicated keyboard layouts for all writing systems (scripts). So many scripts require some additional software which will produce the right Unicodes — this may be an app that installs additional keyboard layouts (or even lets you create your own key mappings), or this can be the Character Map / Character Picker app that comes with your system, where you can click the letters with your mouse, or this can be a special website that includes an HTML character picker or visual keyboard dedicated to the given writing system.

**Comment by twardoch** [comment] 2022-04-08 17:13
Because this is quite complicated, some people have created shortcut solutions, for example fonts where the letters look like Cuneiform or Greek, but actually are mapped to the Unicodes of the Latin script. This is typically called »hack encoding«. 

Hack encoding may look like a simpler solution in the short run, but ultimately, it isn’t. Unicode (where each writing system has its own codes) is much better long-term, and Unicode fonts often have built-in mechanisms that allow automatic formation of ligatures or selection of the right letter forms depending on the surrounding letters (this is important for many writing systems). 

All Noto fonts follow Unicode, so in order to use them, you need some typing solution (keyboard layout, visual kayboard, character map / picker app etc.) that supports Unicode.

**Comment by Mercury13** [comment] 2022-04-08 17:16
@hreyes82, to copy cuneiform chars, you need to open some program that shows them all and copy one by one via clipboard. They have separate codes differing from Latin — unlike all those Wingdings and Webdings.
You may use https://unicode-table.com, it shows lots of character samples, incl. cuneiform (except early dynastic).
Or I’m writing https://mercury13.github.io/unicodia/ — right now it’s Russian only, but I’m going to globalize it, listen to my updates.
If you install the font, you can use this: https://babelstone.co.uk/Software/BabelMap.html  Unlike my Unicodia, it does not bundle all fonts to prevent tofu. Well, for cuneiform my Unicodia bundles namely Noto.

**Comment by Mercury13** [comment] 2022-04-08 17:44
Two updates.
1. Unicode 14.
2. https://r12a.github.io/uniview/ is also a cool thing.

**Comment by Mercury13** [comment] 2022-04-08 17:56
@hreyes82, wait for updates of my Unicodia. In ≈2 months if I do not perish (there’s a war in Ukraine) I’ll globalize it.
